# Workflow Registry Configuration
# 工作流注册表配置 - 自动生成
#
# 生成命令：
#   ./tools/puppy_pipeline/scripts-registry.sh scan-workflows
#   或使用参数：--project "PuppyAgent-Jack" --scope "smoke-test.yml,e2e-fast.yml,e2e.yml"
#
# 使用配置：
#   export WORKFLOW_REGISTRY_FILE=./tools/puppy_pipeline/.workflows.yml
#
# 基于模板：.workflows.template.yml

version: "1.0"

project:
  name: "PuppyAgent-Jack"
  description: "Workflow automation configuration"
  last_updated: "2025-10-19 08:46:11 UTC"
  auto_generated: true
  scope: "smoke-test.yml,e2e-fast.yml,e2e.yml"

workflows:
  - name: "smoke-test.yml"
    description: "快速冒烟测试 - 2-3分钟完成"
    check_window: 180
    expected_duration: 30
    category: "smoke"
    priority: 5
    tags:
      - "fast"
      - "validation"
      - "pre-merge"
      - "smoke"
    metadata:
      workflow_name_field: "smoke-test"
      timeout_minutes: 10
      triggers: "  push,  workflow_dispatch {},"

  - name: "e2e-fast.yml"
    description: "e2e-fast"
    check_window: 360
    expected_duration: 120
    category: "e2e-fast"
    priority: 4
    tags:
      - "e2e"
      - "optimized"
      - "ci"
      - "integration"
    metadata:
      workflow_name_field: "e2e-fast"
      timeout_minutes: 5
      triggers: "  push,  workflow_dispatch {},"

  - name: "e2e.yml"
    description: "e2e"
    check_window: 900
    expected_duration: 300
    category: "e2e-full"
    priority: 3
    tags:
      - "e2e"
      - "comprehensive"
      - "integration"
    metadata:
      workflow_name_field: "e2e"
      timeout_minutes: 60
      triggers: "  push,  workflow_dispatch {},"


# 使用说明
# --------
# 1. 设置环境变量使用此配置：
#    export WORKFLOW_REGISTRY_FILE=./tools/puppy_pipeline/.workflows.yml
#
# 2. 运行watch脚本：
#    ./tools/puppy_pipeline/watch-workflow-bg.sh smoke-test.yml
#
# 3. 更新配置（基于实际运行数据）：
#    ./tools/puppy_pipeline/scripts-registry.sh optimize-workflow smoke-test.yml 25
#
# 4. 重新生成配置（如果workflows有变化）：
#    ./tools/puppy_pipeline/scripts-registry.sh scan-workflows

# 字段说明
# --------
# name:              workflow文件名（唯一标识）
# description:       从workflow文件注释或预设值提取
# check_window:      快速完成检测窗口（秒），默认约为expected_duration的6倍
# expected_duration: 预期运行时长（秒），基于经验预设
# category:          分类标签（smoke|e2e-fast|e2e-full）
# priority:          优先级（1-5，5最高）
# tags:              标签列表，用于过滤和分组
# metadata:          从workflow文件中提取的额外信息

# 优化建议
# --------
# - check_window 应大于 expected_duration 的 6 倍，以应对启动延迟
# - expected_duration 应基于历史运行数据定期更新
# - 使用 optimize-workflow 命令获取基于实际数据的优化建议
