'use client';

import React, { useState, useEffect } from 'react';
import { useAgent, AgentType } from '@/contexts/AgentContext';
import type { Tool as DbTool } from '@/lib/mcpApi';
import { ChatAgentConfig } from './configs/ChatAgentConfig';
import { ScheduleAgentConfig } from './configs/ScheduleAgentConfig';
import { OpenClawAgentConfig } from './configs/OpenClawAgentConfig';
import type { AgentConfigProps } from './configs/ChatAgentConfig';

interface AgentSettingViewProps {
  availableTools?: unknown[];
  projectTools?: DbTool[];
  tableNameById?: Record<string, string>;
  currentTableId?: string;
}

// ── Agent type display config ───────────────────────────────────

const AGENT_TYPE_CONFIG: Record<AgentType, { label: string; icon: React.ReactNode }> = {
  chat: {
    label: 'Chat Agent',
    icon: <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ color: '#999' }}><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" /></svg>,
  },
  schedule: {
    label: 'Schedule',
    icon: <span style={{ fontSize: 14 }}>⏰</span>,
  },
  webhook: {
    label: 'N8N / Zapier',
    icon: <span style={{ fontSize: 14 }}>⚡</span>,
  },
  devbox: {
    label: 'OpenClaw',
    icon: <span style={{ fontSize: 14 }}>🦞</span>,
  },
};

// Webhook config is handled inline here — it is not shown in the type selector
// and is a low-usage path that doesn't warrant its own file yet.
const VISIBLE_AGENT_TYPES: AgentType[] = ['chat', 'schedule', 'devbox'];

// ── Config component registry ───────────────────────────────────

const AGENT_CONFIG_MAP: Record<AgentType, React.ComponentType<AgentConfigProps>> = {
  chat:     ChatAgentConfig,
  schedule: ScheduleAgentConfig,
  devbox:   OpenClawAgentConfig,
  webhook:  ChatAgentConfig, // fallback — webhook not exposed in the type selector
};

// ── Name generator ──────────────────────────────────────────────

const NAME_ADJECTIVES = ['Swift', 'Cosmic', 'Silent', 'Crystal', 'Shadow', 'Golden', 'Iron', 'Silver', 'Neon', 'Phantom', 'Mystic', 'Thunder', 'Frost', 'Solar', 'Lunar', 'Spark', 'Pixel', 'Cyber', 'Atomic', 'Quantum', 'Hyper', 'Ultra', 'Mega', 'Turbo'];
const NAME_NOUNS = ['Fox', 'Wolf', 'Hawk', 'Bear', 'Tiger', 'Dragon', 'Phoenix', 'Raven', 'Node', 'Core', 'Link', 'Pulse', 'Wave', 'Bolt', 'Spark', 'Flux', 'Agent', 'Bot', 'Mind', 'Edge', 'Flow', 'Hub', 'Nexus', 'Sync'];
const generateRandomName = () => {
  const adj = NAME_ADJECTIVES[Math.floor(Math.random() * NAME_ADJECTIVES.length)];
  const noun = NAME_NOUNS[Math.floor(Math.random() * NAME_NOUNS.length)];
  return `${adj} ${noun}`;
};

// ── Close icon (used only in this file) ────────────────────────

const CloseIcon = () => (
  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
  </svg>
);

// ── Main component ──────────────────────────────────────────────

export function AgentSettingView({ projectTools }: AgentSettingViewProps) {
  const {
    draftType,
    setDraftType,
    deployAgent,
    draftResources,
    cancelSetting,
  } = useAgent();

  const [draftName, setDraftName] = useState('');
  const [isEditingName, setIsEditingName] = useState(false);
  const [autoGeneratedName] = useState(() => generateRandomName());

  const displayName = draftName.trim() || autoGeneratedName;
  const hasAnyContent = draftResources.length > 0;

  const labelStyle: React.CSSProperties = {
    fontSize: 13, fontWeight: 500, color: '#666', marginBottom: 8, display: 'block',
  };

  const ActiveConfig = AGENT_CONFIG_MAP[draftType];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>

      {/* Header */}
      <div style={{ height: 48, padding: '0 16px', borderBottom: '1px solid rgba(255,255,255,0.06)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: '#141414' }}>
        <span style={{ fontSize: 14, fontWeight: 500, color: '#666' }}>
          Creating new access
        </span>
        <button
          onClick={cancelSetting}
          style={{ width: 28, height: 28, background: 'transparent', border: 'none', color: '#525252', cursor: 'pointer', borderRadius: 4, display: 'flex', alignItems: 'center', justifyContent: 'center' }}
          onMouseEnter={e => { e.currentTarget.style.color = '#a3a3a3'; e.currentTarget.style.background = '#1f1f1f'; }}
          onMouseLeave={e => { e.currentTarget.style.color = '#525252'; e.currentTarget.style.background = 'transparent'; }}
          title="Close"
        >
          <CloseIcon />
        </button>
      </div>

      {/* Scrollable content */}
      <div style={{ flex: 1, overflowY: 'auto', padding: 16, display: 'flex', flexDirection: 'column', gap: 16 }}>

        {/* Type selector */}
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 4, marginBottom: 8 }}>
            <label style={{ ...labelStyle, marginBottom: 0 }}>Context is used by</label>
            <span style={{ width: 5, height: 5, background: '#ef4444', borderRadius: '50%' }} title="Required" />
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 6 }}>
            {VISIBLE_AGENT_TYPES.map((type) => {
              const cfg = AGENT_TYPE_CONFIG[type];
              const selected = type === draftType;
              return (
                <button
                  key={type}
                  onClick={() => setDraftType(type)}
                  style={{
                    display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
                    gap: 8, padding: '0 4px', height: 80, width: '100%',
                    background: '#161616',
                    border: selected ? '1px solid rgba(34,197,94,0.5)' : '1px solid #2a2a2a',
                    borderRadius: 8, cursor: 'pointer', transition: 'all 0.15s ease', textAlign: 'center',
                  }}
                  onMouseEnter={e => { if (!selected) { e.currentTarget.style.background = '#1a1a1a'; e.currentTarget.style.borderColor = '#333'; } }}
                  onMouseLeave={e => { if (!selected) { e.currentTarget.style.background = '#161616'; e.currentTarget.style.borderColor = '#2a2a2a'; } }}
                >
                  <span style={{ display: 'flex', fontSize: 20, marginBottom: 2 }}>{cfg.icon}</span>
                  <span style={{ fontSize: 12, fontWeight: 500, lineHeight: 1.2, color: selected ? '#e5e5e5' : '#999', maxWidth: '100%', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {cfg.label}
                  </span>
                </button>
              );
            })}
          </div>
        </div>

        {/* Active config — each type owns its own sections */}
        <ActiveConfig projectTools={projectTools} />

        {/* Footer: name + save */}
        <div style={{ marginTop: 'auto', display: 'flex', flexDirection: 'column', gap: 12 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '8px 0', borderTop: '1px solid #1a1a1a' }}>
            <span style={{ width: 32, height: 32, borderRadius: '50%', background: '#1a1a1a', border: '1px solid #2a2a2a', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 16, flexShrink: 0, color: '#999' }}>
              {AGENT_TYPE_CONFIG[draftType]?.icon}
            </span>
            {isEditingName ? (
              <input
                type="text" value={draftName} onChange={e => setDraftName(e.target.value)}
                onBlur={() => setIsEditingName(false)}
                onKeyDown={e => { if (e.key === 'Enter') setIsEditingName(false); }}
                placeholder={autoGeneratedName} autoFocus
                style={{ flex: 1, height: 24, background: '#161616', border: '1px solid #3a3a3a', borderRadius: 4, padding: '0 8px', color: '#e5e5e5', fontSize: 14, outline: 'none' }}
              />
            ) : (
              <button
                onClick={() => setIsEditingName(true)}
                style={{ flex: 1, height: 24, background: 'transparent', border: 'none', borderRadius: 4, padding: '0 4px', color: draftName ? '#e5e5e5' : '#737373', fontSize: 14, cursor: 'text', textAlign: 'left', transition: 'all 0.1s' }}
                onMouseEnter={e => e.currentTarget.style.background = '#1a1a1a'}
                onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
                title="Click to rename"
              >
                {displayName}
              </button>
            )}
          </div>

          <button
            onClick={() => deployAgent(displayName, draftType)}
            disabled={!hasAnyContent}
            style={{ height: 32, background: hasAnyContent ? '#4ade80' : '#262626', color: hasAnyContent ? '#000' : '#525252', border: 'none', borderRadius: 6, cursor: hasAnyContent ? 'pointer' : 'not-allowed', fontSize: 14, fontWeight: 600, transition: 'all 0.15s' }}
            onMouseEnter={e => { if (hasAnyContent) e.currentTarget.style.background = '#22c55e'; }}
            onMouseLeave={e => { if (hasAnyContent) e.currentTarget.style.background = '#4ade80'; }}
          >
            Save
          </button>
        </div>

      </div>
    </div>
  );
}
