"""
MCP data access layer

Provides CRUD operations for the mcp table.
"""

from typing import List, Optional
from supabase import Client

from src.infra.supabase.exceptions import handle_supabase_error
from src.mcp.supabase_schemas import (
    McpCreate,
    McpUpdate,
    McpResponse,
)


class McpRepository:
    """MCP data access repository"""

    def __init__(self, client: Client):
        """
        Initialize repository

        Args:
            client: Supabase client instance
        """
        self._client = client

    def create(self, mcp_data: McpCreate) -> McpResponse:
        """
        Create an MCP instance

        Args:
            mcp_data: MCP creation data

        Returns:
            Created MCP instance data

        Raises:
            SupabaseException: When creation fails
        """
        try:
            data = mcp_data.model_dump(exclude_none=True)
            # Ensure id and created_at are not included (these are auto-generated by the database)
            data.pop("id", None)
            data.pop("created_at", None)
            response = self._client.table("mcps").insert(data).execute()
            return McpResponse(**response.data[0])
        except Exception as e:
            raise handle_supabase_error(e, "create MCP instance")

    def get_by_id(self, mcp_id: int) -> Optional[McpResponse]:
        """
        Get an MCP instance by ID

        Args:
            mcp_id: MCP instance ID

        Returns:
            MCP instance data, or None if not found
        """
        response = (
            self._client.table("mcps").select("*").eq("id", mcp_id).execute()
        )
        if response.data:
            return McpResponse(**response.data[0])
        return None

    def get_by_api_key(self, api_key: str) -> Optional[McpResponse]:
        """
        Get an MCP instance by API Key

        Args:
            api_key: MCP API Key

        Returns:
            MCP instance data, or None if not found
        """
        response = (
            self._client.table("mcps")
            .select("*")
            .eq("api_key", api_key)
            .execute()
        )
        if response.data:
            return McpResponse(**response.data[0])
        return None

    def get_list(
        self,
        skip: int = 0,
        limit: int = 100,
        project_id: Optional[str] = None,
        table_id: Optional[str] = None,
    ) -> List[McpResponse]:
        """
        Get MCP instance list (filtered by project_id, no longer by user_id)

        Args:
            skip: Number of records to skip
            limit: Number of records to return
            project_id: Optional, filter by project ID
            table_id: Optional, filter by table ID

        Returns:
            List of MCP instances
        """
        query = self._client.table("mcps").select("*")

        if project_id is not None:
            query = query.eq("project_id", project_id)

        if table_id is not None:
            query = query.eq("table_id", table_id)

        response = query.range(skip, skip + limit - 1).execute()
        return [McpResponse(**item) for item in response.data]

    def update(self, mcp_id: int, mcp_data: McpUpdate) -> Optional[McpResponse]:
        """
        Update an MCP instance

        Args:
            mcp_id: MCP instance ID
            mcp_data: MCP update data

        Returns:
            Updated MCP instance data, or None if not found

        Raises:
            SupabaseException: When update fails
        """
        try:
            data = mcp_data.model_dump(exclude_none=True)
            if not data:
                return self.get_by_id(mcp_id)

            # Ensure id and created_at are not included
            data.pop("id", None)
            data.pop("created_at", None)

            response = (
                self._client.table("mcps")
                .update(data)
                .eq("id", mcp_id)
                .execute()
            )
            if response.data:
                return McpResponse(**response.data[0])
            return None
        except Exception as e:
            raise handle_supabase_error(e, "update MCP instance")

    def update_by_api_key(
        self, api_key: str, mcp_data: McpUpdate
    ) -> Optional[McpResponse]:
        """
        Update an MCP instance by API Key

        Args:
            api_key: MCP API Key
            mcp_data: MCP update data

        Returns:
            Updated MCP instance data, or None if not found

        Raises:
            SupabaseException: When update fails
        """
        try:
            data = mcp_data.model_dump(exclude_none=True)
            if not data:
                return self.get_by_api_key(api_key)

            # Ensure id and created_at are not included
            data.pop("id", None)
            data.pop("created_at", None)

            response = (
                self._client.table("mcps")
                .update(data)
                .eq("api_key", api_key)
                .execute()
            )
            if response.data:
                return McpResponse(**response.data[0])
            return None
        except Exception as e:
            raise handle_supabase_error(e, "update MCP instance")

    def delete(self, mcp_id: int) -> bool:
        """
        Delete an MCP instance

        Args:
            mcp_id: MCP instance ID

        Returns:
            Whether deletion was successful
        """
        response = (
            self._client.table("mcps").delete().eq("id", mcp_id).execute()
        )
        return len(response.data) > 0

    def delete_by_api_key(self, api_key: str) -> bool:
        """
        Delete an MCP instance by API Key

        Args:
            api_key: MCP API Key

        Returns:
            Whether deletion was successful
        """
        response = (
            self._client.table("mcps").delete().eq("api_key", api_key).execute()
        )
        return len(response.data) > 0
