-- Chunks table for persisted text chunking results
-- Note: Context data table name follows current codebase: public.context_table

create table if not exists public.chunks (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  -- Relationship
  table_id bigint not null,
  json_pointer text not null,

  -- Chunk ordering
  chunk_index integer not null,
  total_chunks integer not null,

  -- Content & position
  chunk_text text not null,
  char_start integer not null,
  char_end integer not null,

  -- Versioning
  content_hash text not null,

  -- Optional: external search engine sync (future work)
  turbopuffer_namespace text null,
  turbopuffer_doc_id text null,

  constraint chunks_pkey primary key (id),
  constraint chunks_table_id_fkey foreign key (table_id) references public.context_table (id) on delete cascade
);

-- Ensure idempotency per node+version+index
create unique index if not exists idx_chunks_unique_node_version_index
on public.chunks (table_id, json_pointer, content_hash, chunk_index);

-- Lookup by node
create index if not exists idx_chunks_table_json_pointer
on public.chunks (table_id, json_pointer);

-- Lookup by content version
create index if not exists idx_chunks_content_hash
on public.chunks (content_hash);

-- Optional uniqueness when using turbopuffer syncing
create unique index if not exists idx_chunks_turbopuffer_doc_id_unique
on public.chunks (turbopuffer_doc_id)
where turbopuffer_doc_id is not null;

