create table public.context_publish (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  user_id uuid not null,
  table_id bigint not null,
  json_path text not null default '',
  publish_key text not null,
  status boolean not null default true,
  expires_at timestamp with time zone not null default (now() + interval '7 days'),
  constraint context_publish_pkey primary key (id),
  constraint context_publish_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
) TABLESPACE pg_default;

create unique index IF not exists context_publish_publish_key_uniq on public.context_publish using btree (publish_key) TABLESPACE pg_default;
create index IF not exists context_publish_user_id_created_at_idx on public.context_publish using btree (user_id, created_at desc) TABLESPACE pg_default;
create index IF not exists context_publish_expires_at_idx on public.context_publish using btree (expires_at) TABLESPACE pg_default;


