create table public.etl_rule (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  name text null default ''::text,
  description text null default ''::text,
  json_schema jsonb null,
  system_prompt text null default ''::text,
  user_id bigint null,
  constraint etl_rules_pkey primary key (id),
  constraint etl_rules_user_id_fkey foreign KEY (user_id) references user_temp (id)
) TABLESPACE pg_default;