create table public.mcp (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  api_key text null,
  user_id bigint null,
  project_id bigint null,
  table_id bigint null,
  json_path text null,
  status boolean null,
  port bigint null,
  docker_info jsonb null,
  tools_definition jsonb null,
  register_tools jsonb null,
  preview_keys jsonb null,
  constraint mcp_pkey primary key (id),
  constraint mcp_project_id_fkey foreign KEY (project_id) references project (id),
  constraint mcp_table_id_fkey foreign KEY (table_id) references "table" (id),
  constraint mcp_user_id_fkey foreign KEY (user_id) references user_temp (id)
) TABLESPACE pg_default;