create table public.mcp_binding (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  mcp_id bigint not null,
  tool_id bigint not null,
  status boolean not null default true,

  constraint mcp_binding_pkey primary key (id),
  constraint mcp_binding_mcp_id_fkey foreign key (mcp_id)
    references public.mcp_v2 (id) on delete cascade,
  constraint mcp_binding_tool_id_fkey foreign key (tool_id)
    references public.tool (id) on delete cascade,
  constraint mcp_binding_mcp_id_tool_id_key unique (mcp_id, tool_id)
) tablespace pg_default;

create index if not exists mcp_binding_mcp_id_idx
  on public.mcp_binding using btree (mcp_id) tablespace pg_default;

create index if not exists mcp_binding_tool_id_idx
  on public.mcp_binding using btree (tool_id) tablespace pg_default;

create index if not exists mcp_binding_mcp_id_created_at_idx
  on public.mcp_binding using btree (mcp_id, created_at desc) tablespace pg_default;