create table public.mcp_v2 (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  user_id uuid not null,
  name text null,
  api_key text null,
  status boolean null default false,
  constraint mcp_v2_pkey primary key (id),
  constraint mcp_v2_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint mcp_v2_user_id_fkey1 foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

create index IF not exists mcp_v2_user_id_created_at_idx on public.mcp_v2 using btree (user_id, created_at desc) TABLESPACE pg_default;

create index IF not exists mcp_v2_api_key_idx on public.mcp_v2 using btree (api_key) TABLESPACE pg_default;