create table public.oauth_connection (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  access_token text not null,
  refresh_token text null,
  token_type text null,
  expires_at timestamp with time zone null,
  workspace_id text null,
  workspace_name text null,
  bot_id text null,
  metadata jsonb null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint oauth_connection_user_provider_unique unique (user_id, provider)
);

-- 创建索引
create index oauth_connection_user_id_idx on public.oauth_connection(user_id);
create index oauth_connection_provider_idx on public.oauth_connection(provider);

-- 添加注释
comment on table public.oauth_connection is 'OAuth连接表，用于存储第三方平台的授权信息';
comment on column public.oauth_connection.provider is 'OAuth提供商名称，如 notion, github 等';
comment on column public.oauth_connection.access_token is 'OAuth访问令牌';
comment on column public.oauth_connection.refresh_token is 'OAuth刷新令牌';
comment on column public.oauth_connection.token_type is '令牌类型，如 Bearer';
comment on column public.oauth_connection.expires_at is '令牌过期时间';
comment on column public.oauth_connection.workspace_id is '第三方平台的工作区ID';
comment on column public.oauth_connection.workspace_name is '第三方平台的工作区名称';
comment on column public.oauth_connection.bot_id is 'Bot ID，适用于某些平台';
comment on column public.oauth_connection.metadata is '额外的元数据信息';

-- 创建更新时间触发器
create or replace function update_oauth_connection_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger oauth_connection_updated_at
  before update on public.oauth_connection
  for each row
  execute function update_oauth_connection_updated_at();