create table public.project (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  description text null,
  user_id bigint null,
  constraint project_pkey primary key (id),
  constraint project_user_id_fkey foreign KEY (user_id) references user_temp (id)
) TABLESPACE pg_default;