-- Search indexing task status table
-- Tracks async indexing progress for Search Tools

create table if not exists public.search_index_task (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  -- Relationship
  tool_id bigint not null,
  user_id uuid null,
  project_id bigint null,
  table_id bigint not null,
  json_path text not null default '',

  -- Status
  status text not null default 'pending', -- pending/indexing/ready/error
  started_at timestamp with time zone null,
  finished_at timestamp with time zone null,

  -- Stats
  nodes_count integer null,
  chunks_count integer null,
  indexed_chunks_count integer null,

  -- Errors
  last_error text null,

  constraint search_index_task_pkey primary key (id),
  constraint search_index_task_tool_id_fkey foreign key (tool_id) references public.tool (id) on delete cascade
);

-- One active task per tool (simplest model)
create unique index if not exists idx_search_index_task_tool_id_unique
on public.search_index_task (tool_id);

create index if not exists idx_search_index_task_table_id
on public.search_index_task (table_id);

