create table public.tool (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null,
  table_id bigint null,
  json_path text null,
  type text null,
  name text null,
  alias text null,
  description text null,
  input_schema jsonb null,
  output_schema jsonb null,
  metadata jsonb null,
  constraint tool_pkey primary key (id),
  constraint tool_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;