/**
 * File Format Registry — the single source of truth.
 *
 * Coverage targets the union of:
 *   - Anything VS Code recognizes by default (no extensions
 *     installed) — every Monaco built-in language.
 *   - Anything Obsidian renders by default — markdown, images,
 *     audio, video, PDF.
 *   - Common desktop file types people drop in (office docs,
 *     archives, fonts, ebooks, …) — even if we only show a labeled
 *     placeholder, identification matters for the file tree.
 *
 * To add a new format:
 *   1. Add an entry below.
 *   2. Mirror it in `backend/src/infra/file_formats/registry.py`.
 *
 * Resolution order:
 *   - Exact filename match (for `Makefile` / `Dockerfile` / `README`).
 *   - Extension match (longest-suffix wins — `.tar.gz` beats `.gz`).
 *   - Mime match (server-detected fallback, less reliable).
 */

import type { FileFormat } from './types';

export const FILE_FORMATS: FileFormat[] = [
  // ─── Markdown ───────────────────────────────────────────────────
  {
    id: 'markdown',
    label: 'Markdown',
    extensions: ['.md', '.markdown', '.mdx', '.mkd', '.mdown'],
    mimeTypes: ['text/markdown'],
    category: 'markdown',
    defaultViewer: 'markdown-editor',
    availableViewers: ['markdown-editor', 'monaco-code'],
    editable: true,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'markdown',
  },

  // ─── Structured data ────────────────────────────────────────────
  {
    id: 'json',
    label: 'JSON',
    extensions: ['.json', '.json5', '.jsonc'],
    mimeTypes: ['application/json'],
    category: 'data',
    defaultViewer: 'json-table',
    availableViewers: ['json-table', 'monaco-code'],
    editable: true,
    ingestStrategy: 'parse-structured',
    monacoLanguage: 'json',
  },
  {
    id: 'jsonl',
    label: 'JSON Lines',
    extensions: ['.jsonl', '.ndjson'],
    mimeTypes: ['application/x-ndjson', 'application/jsonl'],
    category: 'data',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'json',
  },
  {
    id: 'yaml',
    label: 'YAML',
    extensions: ['.yaml', '.yml'],
    mimeTypes: ['application/yaml', 'text/yaml', 'text/x-yaml'],
    category: 'data',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'yaml',
  },
  {
    id: 'toml',
    label: 'TOML',
    extensions: ['.toml'],
    mimeTypes: ['application/toml', 'text/toml'],
    category: 'data',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'plaintext',
  },
  {
    id: 'xml',
    label: 'XML',
    extensions: ['.xml', '.plist', '.rss', '.atom', '.xsl', '.xsd', '.svg-xml'],
    mimeTypes: ['application/xml', 'text/xml'],
    category: 'data',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'xml',
  },
  {
    id: 'csv',
    label: 'CSV',
    extensions: ['.csv'],
    mimeTypes: ['text/csv'],
    category: 'data',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'plaintext',
  },
  {
    id: 'tsv',
    label: 'TSV',
    extensions: ['.tsv'],
    mimeTypes: ['text/tab-separated-values'],
    category: 'data',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'plaintext',
  },
  {
    id: 'protobuf',
    label: 'Protocol Buffers',
    extensions: ['.proto'],
    mimeTypes: ['text/x-protobuf'],
    category: 'data',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'protobuf',
  },
  {
    id: 'ini',
    label: 'INI Config',
    extensions: ['.ini', '.cfg', '.conf', '.config', '.editorconfig', '.gitconfig'],
    mimeTypes: ['text/x-ini', 'text/plain'],
    category: 'data',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'ini',
  },
  {
    id: 'properties',
    label: 'Properties',
    extensions: ['.properties'],
    mimeTypes: ['text/x-properties'],
    category: 'data',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'ini',
  },
  {
    id: 'hcl',
    label: 'HCL / Terraform',
    extensions: ['.hcl', '.tf', '.tfvars'],
    mimeTypes: ['text/x-hcl'],
    category: 'data',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'hcl',
  },

  // ─── Code — TS/JS/Web ───────────────────────────────────────────
  {
    id: 'typescript',
    label: 'TypeScript',
    extensions: ['.ts', '.tsx', '.mts', '.cts'],
    mimeTypes: ['application/typescript', 'text/typescript'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'typescript',
  },
  {
    id: 'javascript',
    label: 'JavaScript',
    extensions: ['.js', '.jsx', '.mjs', '.cjs'],
    mimeTypes: ['application/javascript', 'text/javascript'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'javascript',
  },
  {
    id: 'coffeescript',
    label: 'CoffeeScript',
    extensions: ['.coffee'],
    mimeTypes: ['application/vnd.coffeescript'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'coffeescript',
  },
  {
    id: 'html',
    label: 'HTML',
    extensions: ['.html', '.htm', '.xhtml'],
    mimeTypes: ['text/html'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'html',
  },
  {
    id: 'css',
    label: 'CSS',
    extensions: ['.css'],
    mimeTypes: ['text/css'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'css',
  },
  {
    id: 'scss',
    label: 'SCSS',
    extensions: ['.scss', '.sass'],
    mimeTypes: ['text/x-scss', 'text/x-sass'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'scss',
  },
  {
    id: 'less',
    label: 'Less',
    extensions: ['.less'],
    mimeTypes: ['text/x-less'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'less',
  },
  {
    id: 'pug',
    label: 'Pug',
    extensions: ['.pug', '.jade'],
    mimeTypes: ['text/x-pug'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'pug',
  },
  {
    id: 'handlebars',
    label: 'Handlebars',
    extensions: ['.hbs', '.handlebars', '.mustache'],
    mimeTypes: ['text/x-handlebars-template'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'handlebars',
  },
  {
    id: 'razor',
    label: 'Razor',
    extensions: ['.cshtml', '.razor'],
    mimeTypes: ['text/x-cshtml'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'razor',
  },
  {
    id: 'twig',
    label: 'Twig',
    extensions: ['.twig'],
    mimeTypes: ['text/x-twig'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'twig',
  },
  {
    id: 'liquid',
    label: 'Liquid',
    extensions: ['.liquid'],
    mimeTypes: ['text/x-liquid'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'liquid',
  },

  // ─── Code — Backend / Systems ───────────────────────────────────
  {
    id: 'python',
    label: 'Python',
    extensions: ['.py', '.pyw', '.pyi', '.pyx'],
    mimeTypes: ['text/x-python', 'application/x-python'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'python',
  },
  {
    id: 'ruby',
    label: 'Ruby',
    extensions: ['.rb', '.rake', '.gemspec', '.ru'],
    filenames: [
      'Rakefile', 'Gemfile', 'Capfile', 'Berksfile', 'Brewfile',
      'Cheffile', 'Podfile', 'Fastfile', 'Appfile', 'Deliverfile',
      'Snapfile', 'Matchfile', 'Vagrantfile', 'Guardfile', 'Procfile',
    ],
    mimeTypes: ['text/x-ruby', 'application/x-ruby'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'ruby',
  },
  {
    id: 'rust',
    label: 'Rust',
    extensions: ['.rs'],
    mimeTypes: ['text/x-rust'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'rust',
  },
  {
    id: 'go',
    label: 'Go',
    extensions: ['.go'],
    mimeTypes: ['text/x-go'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'go',
  },
  {
    id: 'java',
    label: 'Java',
    extensions: ['.java'],
    mimeTypes: ['text/x-java', 'text/x-java-source'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'java',
  },
  {
    id: 'kotlin',
    label: 'Kotlin',
    extensions: ['.kt', '.kts'],
    mimeTypes: ['text/x-kotlin'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'kotlin',
  },
  {
    id: 'swift',
    label: 'Swift',
    extensions: ['.swift'],
    mimeTypes: ['text/x-swift'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'swift',
  },
  {
    id: 'objective-c',
    label: 'Objective-C',
    extensions: ['.m', '.mm'],
    mimeTypes: ['text/x-objectivec'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'objective-c',
  },
  {
    id: 'c',
    label: 'C',
    extensions: ['.c', '.h'],
    mimeTypes: ['text/x-c', 'text/x-csrc'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'c',
  },
  {
    id: 'cpp',
    label: 'C++',
    extensions: ['.cpp', '.cc', '.cxx', '.hpp', '.hh', '.hxx', '.ipp', '.tpp'],
    mimeTypes: ['text/x-c++', 'text/x-c++src'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'cpp',
  },
  {
    id: 'csharp',
    label: 'C#',
    extensions: ['.cs', '.csx'],
    mimeTypes: ['text/x-csharp'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'csharp',
  },
  {
    id: 'fsharp',
    label: 'F#',
    extensions: ['.fs', '.fsi', '.fsx', '.fsscript'],
    mimeTypes: ['text/x-fsharp'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'fsharp',
  },
  {
    id: 'visualbasic',
    label: 'Visual Basic',
    extensions: ['.vb', '.vbs'],
    mimeTypes: ['text/x-vb'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'vb',
  },
  {
    id: 'pascal',
    label: 'Pascal',
    extensions: ['.pas', '.pp', '.dpr'],
    mimeTypes: ['text/x-pascal'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'pascal',
  },
  {
    id: 'haskell',
    label: 'Haskell',
    extensions: ['.hs', '.lhs'],
    mimeTypes: ['text/x-haskell'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'plaintext',
  },
  {
    id: 'erlang',
    label: 'Erlang',
    extensions: ['.erl', '.hrl'],
    mimeTypes: ['text/x-erlang'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'plaintext',
  },
  {
    id: 'elixir',
    label: 'Elixir',
    extensions: ['.ex', '.exs', '.eex', '.heex', '.leex'],
    mimeTypes: ['text/x-elixir'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'elixir',
  },
  {
    id: 'clojure',
    label: 'Clojure',
    extensions: ['.clj', '.cljs', '.cljc', '.edn'],
    mimeTypes: ['text/x-clojure'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'clojure',
  },
  {
    id: 'scala',
    label: 'Scala',
    extensions: ['.scala', '.sc'],
    mimeTypes: ['text/x-scala'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'scala',
  },
  {
    id: 'dart',
    label: 'Dart',
    extensions: ['.dart'],
    mimeTypes: ['application/dart'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'dart',
  },
  {
    id: 'julia',
    label: 'Julia',
    extensions: ['.jl'],
    mimeTypes: ['text/x-julia'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'julia',
  },
  {
    id: 'r',
    label: 'R',
    extensions: ['.r', '.rmd'],
    mimeTypes: ['text/x-r'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'r',
  },
  {
    id: 'lua',
    label: 'Lua',
    extensions: ['.lua'],
    mimeTypes: ['text/x-lua', 'application/x-lua'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'lua',
  },
  {
    id: 'perl',
    label: 'Perl',
    extensions: ['.pl', '.pm', '.t', '.pod'],
    mimeTypes: ['text/x-perl'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'perl',
  },
  {
    id: 'php',
    label: 'PHP',
    extensions: ['.php', '.phtml', '.phar'],
    mimeTypes: ['application/x-php', 'text/x-php'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'php',
  },
  {
    id: 'shell',
    label: 'Shell',
    extensions: ['.sh', '.bash', '.zsh', '.fish', '.ash', '.ksh'],
    mimeTypes: ['application/x-sh', 'text/x-shellscript'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'shell',
  },
  {
    id: 'powershell',
    label: 'PowerShell',
    extensions: ['.ps1', '.psm1', '.psd1'],
    mimeTypes: ['application/x-powershell'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'powershell',
  },
  {
    id: 'batch',
    label: 'Batch',
    extensions: ['.bat', '.cmd'],
    mimeTypes: ['application/x-bat'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'bat',
  },
  {
    id: 'tcl',
    label: 'Tcl',
    extensions: ['.tcl'],
    mimeTypes: ['application/x-tcl'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'plaintext',
  },
  {
    id: 'sql',
    label: 'SQL',
    extensions: ['.sql', '.psql', '.mysql'],
    mimeTypes: ['application/sql', 'text/x-sql'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'sql',
  },
  {
    id: 'graphql',
    label: 'GraphQL',
    extensions: ['.graphql', '.gql'],
    mimeTypes: ['application/graphql'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'graphql',
  },
  {
    id: 'solidity',
    label: 'Solidity',
    extensions: ['.sol'],
    mimeTypes: ['text/x-solidity'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'sol',
  },
  {
    id: 'verilog',
    label: 'Verilog / SystemVerilog',
    extensions: ['.v', '.sv', '.vh', '.svh'],
    mimeTypes: ['text/x-verilog', 'text/x-systemverilog'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'systemverilog',
  },

  // ─── Build / Infra files ────────────────────────────────────────
  {
    id: 'dockerfile',
    label: 'Dockerfile',
    extensions: ['.dockerfile'],
    filenames: ['Dockerfile', 'Containerfile'],
    mimeTypes: ['text/x-dockerfile'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'dockerfile',
  },
  {
    id: 'makefile',
    label: 'Makefile',
    extensions: ['.mk', '.mak'],
    filenames: ['Makefile', 'GNUmakefile', 'makefile'],
    mimeTypes: ['text/x-makefile'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'plaintext',
  },
  {
    id: 'cmake',
    label: 'CMake',
    extensions: ['.cmake'],
    filenames: ['CMakeLists.txt'],
    mimeTypes: ['text/x-cmake'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'plaintext',
  },
  {
    id: 'tex',
    label: 'TeX / LaTeX',
    extensions: ['.tex', '.latex', '.ltx', '.sty', '.cls', '.bib'],
    mimeTypes: ['application/x-tex', 'application/x-latex'],
    category: 'code',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'latex',
  },
  {
    id: 'restructuredtext',
    label: 'reStructuredText',
    extensions: ['.rst'],
    mimeTypes: ['text/x-rst'],
    category: 'text',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'restructuredtext',
  },
  {
    id: 'diff',
    label: 'Diff / Patch',
    extensions: ['.diff', '.patch'],
    mimeTypes: ['text/x-diff', 'text/x-patch'],
    category: 'text',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'plaintext',
  },

  // ─── Plain text + extensionless metadata files ──────────────────
  {
    id: 'plaintext',
    label: 'Plain Text',
    extensions: ['.txt', '.text', '.log', '.env'],
    filenames: [
      'README', 'LICENSE', 'COPYING', 'INSTALL', 'AUTHORS',
      'CONTRIBUTORS', 'NOTICE', 'CHANGELOG', 'CHANGES', 'HISTORY',
      'TODO', 'NEWS', 'CREDITS', 'MAINTAINERS', 'VERSION',
    ],
    mimeTypes: ['text/plain'],
    category: 'text',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'plaintext',
  },

  // ─── Subtitles ──────────────────────────────────────────────────
  {
    id: 'subtitle-srt',
    label: 'SubRip Subtitle',
    extensions: ['.srt'],
    mimeTypes: ['application/x-subrip'],
    category: 'text',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'plaintext',
  },
  {
    id: 'subtitle-vtt',
    label: 'WebVTT Subtitle',
    extensions: ['.vtt'],
    mimeTypes: ['text/vtt'],
    category: 'text',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'plaintext',
  },
  {
    id: 'subtitle-ass',
    label: 'ASS / SSA Subtitle',
    extensions: ['.ass', '.ssa'],
    mimeTypes: ['text/x-ass'],
    category: 'text',
    defaultViewer: 'monaco-code',
    editable: false,
    ingestStrategy: 'parse-text',
    monacoLanguage: 'plaintext',
  },

  // ─── Images ─────────────────────────────────────────────────────
  {
    id: 'png',
    label: 'PNG Image',
    extensions: ['.png', '.apng'],
    mimeTypes: ['image/png', 'image/apng'],
    category: 'image',
    defaultViewer: 'image-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'jpeg',
    label: 'JPEG Image',
    extensions: ['.jpg', '.jpeg', '.jpe', '.jfif', '.pjpeg', '.pjp'],
    mimeTypes: ['image/jpeg'],
    category: 'image',
    defaultViewer: 'image-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'gif',
    label: 'GIF Image',
    extensions: ['.gif'],
    mimeTypes: ['image/gif'],
    category: 'image',
    defaultViewer: 'image-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'webp',
    label: 'WebP Image',
    extensions: ['.webp'],
    mimeTypes: ['image/webp'],
    category: 'image',
    defaultViewer: 'image-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'avif',
    label: 'AVIF Image',
    extensions: ['.avif'],
    mimeTypes: ['image/avif'],
    category: 'image',
    defaultViewer: 'image-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'svg',
    label: 'SVG Image',
    extensions: ['.svg'],
    mimeTypes: ['image/svg+xml'],
    category: 'image',
    defaultViewer: 'image-preview',
    availableViewers: ['image-preview', 'monaco-code'],
    editable: false,
    ingestStrategy: 'raw',
    monacoLanguage: 'xml',
  },
  {
    id: 'bmp',
    label: 'Bitmap Image',
    extensions: ['.bmp'],
    mimeTypes: ['image/bmp'],
    category: 'image',
    defaultViewer: 'image-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'ico',
    label: 'Icon',
    extensions: ['.ico'],
    mimeTypes: ['image/x-icon', 'image/vnd.microsoft.icon'],
    category: 'image',
    defaultViewer: 'image-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'tiff',
    // Browsers don't decode TIFF natively (Safari kinda does), so
    // we route to placeholder to avoid a broken image.
    label: 'TIFF Image',
    extensions: ['.tif', '.tiff'],
    mimeTypes: ['image/tiff'],
    category: 'image',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'heic',
    label: 'HEIC Image',
    // Browsers can't decode HEIC, but we still want a recognizable
    // entry so the placeholder shows the right label.
    extensions: ['.heic', '.heif'],
    mimeTypes: ['image/heic', 'image/heif'],
    category: 'image',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'raw-photo',
    label: 'RAW Photo',
    extensions: ['.raw', '.cr2', '.cr3', '.nef', '.arw', '.dng', '.orf', '.rw2'],
    mimeTypes: ['image/x-raw', 'image/x-canon-cr2', 'image/x-nikon-nef'],
    category: 'image',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'photoshop',
    label: 'Photoshop Document',
    extensions: ['.psd'],
    mimeTypes: ['image/vnd.adobe.photoshop'],
    category: 'image',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },

  // ─── Audio ──────────────────────────────────────────────────────
  {
    id: 'mp3',
    label: 'MP3 Audio',
    extensions: ['.mp3'],
    mimeTypes: ['audio/mpeg', 'audio/mp3'],
    category: 'audio',
    defaultViewer: 'audio-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'wav',
    label: 'WAV Audio',
    extensions: ['.wav', '.wave'],
    mimeTypes: ['audio/wav', 'audio/x-wav'],
    category: 'audio',
    defaultViewer: 'audio-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'ogg-audio',
    label: 'OGG Audio',
    extensions: ['.ogg', '.oga', '.opus'],
    mimeTypes: ['audio/ogg', 'audio/opus'],
    category: 'audio',
    defaultViewer: 'audio-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'm4a',
    label: 'M4A Audio',
    extensions: ['.m4a', '.m4b'],
    mimeTypes: ['audio/mp4', 'audio/x-m4a'],
    category: 'audio',
    defaultViewer: 'audio-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'flac',
    label: 'FLAC Audio',
    extensions: ['.flac'],
    mimeTypes: ['audio/flac', 'audio/x-flac'],
    category: 'audio',
    defaultViewer: 'audio-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'aac',
    label: 'AAC Audio',
    extensions: ['.aac'],
    mimeTypes: ['audio/aac'],
    category: 'audio',
    defaultViewer: 'audio-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'webm-audio',
    label: 'WebM Audio',
    extensions: ['.weba'],
    mimeTypes: ['audio/webm'],
    category: 'audio',
    defaultViewer: 'audio-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'aiff',
    label: 'AIFF Audio',
    // Some browsers (Safari) can decode AIFF — try to play, fall
    // back to native controls error UI.
    extensions: ['.aiff', '.aif', '.aifc'],
    mimeTypes: ['audio/aiff', 'audio/x-aiff'],
    category: 'audio',
    defaultViewer: 'audio-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'wma',
    label: 'Windows Media Audio',
    extensions: ['.wma'],
    mimeTypes: ['audio/x-ms-wma'],
    category: 'audio',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'midi',
    label: 'MIDI',
    extensions: ['.mid', '.midi'],
    mimeTypes: ['audio/midi', 'audio/x-midi'],
    category: 'audio',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },

  // ─── Video ──────────────────────────────────────────────────────
  {
    id: 'mp4',
    label: 'MP4 Video',
    extensions: ['.mp4', '.m4v'],
    mimeTypes: ['video/mp4'],
    category: 'video',
    defaultViewer: 'video-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'webm-video',
    label: 'WebM Video',
    extensions: ['.webm'],
    mimeTypes: ['video/webm'],
    category: 'video',
    defaultViewer: 'video-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'ogv',
    label: 'OGG Video',
    extensions: ['.ogv'],
    mimeTypes: ['video/ogg'],
    category: 'video',
    defaultViewer: 'video-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'mov',
    // Many .mov files are actually H.264/AAC and play in Safari +
    // Chrome on macOS. Try, fall back gracefully on failure.
    label: 'QuickTime Video',
    extensions: ['.mov', '.qt'],
    mimeTypes: ['video/quicktime'],
    category: 'video',
    defaultViewer: 'video-preview',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'avi',
    label: 'AVI Video',
    extensions: ['.avi'],
    mimeTypes: ['video/x-msvideo'],
    category: 'video',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'mkv',
    label: 'Matroska Video',
    extensions: ['.mkv'],
    mimeTypes: ['video/x-matroska'],
    category: 'video',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'wmv',
    label: 'Windows Media Video',
    extensions: ['.wmv'],
    mimeTypes: ['video/x-ms-wmv'],
    category: 'video',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'flv',
    label: 'Flash Video',
    extensions: ['.flv'],
    mimeTypes: ['video/x-flv'],
    category: 'video',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'mpeg-video',
    label: 'MPEG Video',
    extensions: ['.mpg', '.mpeg', '.mpe', '.m2v'],
    mimeTypes: ['video/mpeg'],
    category: 'video',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'three-gp',
    label: '3GP Video',
    extensions: ['.3gp', '.3gpp', '.3g2'],
    mimeTypes: ['video/3gpp', 'video/3gpp2'],
    category: 'video',
    defaultViewer: 'video-preview',
    editable: false,
    ingestStrategy: 'raw',
  },

  // ─── Documents ──────────────────────────────────────────────────
  {
    id: 'pdf',
    label: 'PDF Document',
    extensions: ['.pdf'],
    mimeTypes: ['application/pdf'],
    category: 'document',
    defaultViewer: 'pdf-preview',
    editable: false,
    ingestStrategy: 'ocr',
  },
  // Microsoft Office — recognized + OCR-ingested, displayed as
  // labeled placeholders. Add a viewer (mammoth / sheetjs) later
  // and just flip `defaultViewer`.
  {
    id: 'docx',
    label: 'Word Document',
    extensions: ['.docx', '.doc'],
    mimeTypes: [
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/msword',
    ],
    category: 'document',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'ocr',
  },
  {
    id: 'xlsx',
    label: 'Excel Spreadsheet',
    extensions: ['.xlsx', '.xls', '.xlsm', '.xlsb'],
    mimeTypes: [
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-excel',
    ],
    category: 'document',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'ocr',
  },
  {
    id: 'pptx',
    label: 'PowerPoint',
    extensions: ['.pptx', '.ppt', '.pps', '.ppsx'],
    mimeTypes: [
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'application/vnd.ms-powerpoint',
    ],
    category: 'document',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'ocr',
  },
  // OpenDocument (LibreOffice)
  {
    id: 'odt',
    label: 'OpenDocument Text',
    extensions: ['.odt', '.ott'],
    mimeTypes: ['application/vnd.oasis.opendocument.text'],
    category: 'document',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'ocr',
  },
  {
    id: 'ods',
    label: 'OpenDocument Spreadsheet',
    extensions: ['.ods', '.ots'],
    mimeTypes: ['application/vnd.oasis.opendocument.spreadsheet'],
    category: 'document',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'ocr',
  },
  {
    id: 'odp',
    label: 'OpenDocument Presentation',
    extensions: ['.odp', '.otp'],
    mimeTypes: ['application/vnd.oasis.opendocument.presentation'],
    category: 'document',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'ocr',
  },
  // Apple iWork
  {
    id: 'pages',
    label: 'Pages Document',
    extensions: ['.pages'],
    mimeTypes: ['application/x-iwork-pages-sffpages'],
    category: 'document',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'numbers',
    label: 'Numbers Spreadsheet',
    extensions: ['.numbers'],
    mimeTypes: ['application/x-iwork-numbers-sffnumbers'],
    category: 'document',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  // Apple Keynote `.key` conflicts with SSL `.key` private keys.
  // We resolve `.key` as a certificate (much more common in code
  // projects); Keynote files only get registered via mime fallback.
  {
    id: 'keynote',
    label: 'Keynote Presentation',
    extensions: [],
    mimeTypes: ['application/x-iwork-keynote-sffkey'],
    category: 'document',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  // Rich text / e-books
  {
    id: 'rtf',
    label: 'Rich Text',
    extensions: ['.rtf'],
    mimeTypes: ['application/rtf', 'text/rtf'],
    category: 'document',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'ocr',
  },
  {
    id: 'epub',
    label: 'EPUB Book',
    extensions: ['.epub'],
    mimeTypes: ['application/epub+zip'],
    category: 'document',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'ocr',
  },
  {
    id: 'mobi',
    label: 'Kindle Book',
    extensions: ['.mobi', '.azw', '.azw3'],
    mimeTypes: ['application/x-mobipocket-ebook'],
    category: 'document',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'ocr',
  },
  // Jupyter — recognized as JSON-shaped but kept in `document`
  // until a real notebook viewer is built.
  {
    id: 'jupyter',
    label: 'Jupyter Notebook',
    extensions: ['.ipynb'],
    mimeTypes: ['application/x-ipynb+json'],
    category: 'document',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'parse-structured',
  },

  // ─── Archives ───────────────────────────────────────────────────
  {
    id: 'zip',
    label: 'ZIP Archive',
    extensions: ['.zip'],
    mimeTypes: ['application/zip', 'application/x-zip-compressed'],
    category: 'archive',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'tar',
    label: 'TAR Archive',
    extensions: ['.tar', '.tar.gz', '.tgz', '.tar.bz2', '.tbz', '.tbz2', '.tar.xz', '.txz'],
    mimeTypes: ['application/x-tar', 'application/gzip'],
    category: 'archive',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'gzip',
    label: 'Gzip',
    extensions: ['.gz'],
    mimeTypes: ['application/gzip'],
    category: 'archive',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'bzip2',
    label: 'Bzip2',
    extensions: ['.bz2', '.bz'],
    mimeTypes: ['application/x-bzip2'],
    category: 'archive',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'xz',
    label: 'XZ',
    extensions: ['.xz', '.lzma'],
    mimeTypes: ['application/x-xz', 'application/x-lzma'],
    category: 'archive',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: '7zip',
    label: '7-Zip Archive',
    extensions: ['.7z'],
    mimeTypes: ['application/x-7z-compressed'],
    category: 'archive',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'rar',
    label: 'RAR Archive',
    extensions: ['.rar'],
    mimeTypes: ['application/vnd.rar', 'application/x-rar-compressed'],
    category: 'archive',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'dmg',
    label: 'macOS Disk Image',
    extensions: ['.dmg'],
    mimeTypes: ['application/x-apple-diskimage'],
    category: 'archive',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'iso',
    label: 'Disc Image',
    extensions: ['.iso', '.img'],
    mimeTypes: ['application/x-iso9660-image'],
    category: 'archive',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },

  // ─── Fonts ──────────────────────────────────────────────────────
  {
    id: 'truetype',
    label: 'TrueType Font',
    extensions: ['.ttf', '.ttc'],
    mimeTypes: ['font/ttf', 'application/x-font-ttf'],
    category: 'binary',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'opentype',
    label: 'OpenType Font',
    extensions: ['.otf'],
    mimeTypes: ['font/otf', 'application/x-font-otf'],
    category: 'binary',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'woff',
    label: 'Web Font',
    extensions: ['.woff', '.woff2'],
    mimeTypes: ['font/woff', 'font/woff2'],
    category: 'binary',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'eot',
    label: 'Embedded OpenType',
    extensions: ['.eot'],
    mimeTypes: ['application/vnd.ms-fontobject'],
    category: 'binary',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },

  // ─── Database / 3D / Misc binary ────────────────────────────────
  {
    id: 'sqlite',
    label: 'SQLite Database',
    extensions: ['.db', '.sqlite', '.sqlite3', '.db3'],
    mimeTypes: ['application/vnd.sqlite3', 'application/x-sqlite3'],
    category: 'binary',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'three-d',
    label: '3D Model',
    extensions: ['.obj', '.stl', '.gltf', '.glb', '.fbx', '.dae', '.ply'],
    mimeTypes: ['model/obj', 'model/stl', 'model/gltf+json', 'model/gltf-binary'],
    category: 'binary',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'cert',
    label: 'Certificate / Key',
    extensions: ['.pem', '.crt', '.cer', '.der', '.key', '.pub', '.csr', '.p12', '.pfx'],
    mimeTypes: [
      'application/x-pem-file',
      'application/x-x509-ca-cert',
      'application/pkix-cert',
    ],
    category: 'binary',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
  {
    id: 'executable',
    label: 'Executable',
    extensions: ['.exe', '.dll', '.so', '.dylib', '.app', '.msi', '.deb', '.rpm', '.pkg', '.apk', '.ipa'],
    mimeTypes: ['application/x-msdownload', 'application/vnd.android.package-archive'],
    category: 'binary',
    defaultViewer: 'binary-placeholder',
    editable: false,
    ingestStrategy: 'raw',
  },
];

/**
 * Fallback when nothing matches — generic binary file.
 * Always exported so callers don't have to handle `undefined`.
 */
export const UNKNOWN_FORMAT: FileFormat = {
  id: 'unknown',
  label: 'File',
  extensions: [],
  mimeTypes: ['application/octet-stream'],
  category: 'binary',
  defaultViewer: 'binary-placeholder',
  editable: false,
  ingestStrategy: 'raw',
};
