name: Template feedback
description: Suggest improvements to PR templates or CONTRIBUTING docs
title: "Template feedback: <short summary>"
labels:
  - template:feedback
  - docs
body:
  - type: dropdown
    id: target
    attributes:
      label: Target
      options:
        - feature
        - bugfix
        - perf
        - refactor
        - ci
        - docs
        - contributing.md
        - other
    validations:
      required: true
  - type: checkboxes
    id: kind
    attributes:
      label: What is this?
      options:
        - label: Missing section
        - label: Confusing wording
        - label: Too long/verbose
        - label: Needs example
        - label: Not applicable to my case
  - type: textarea
    id: details
    attributes:
      label: Details
      description: What happened? What would you change?
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Related PRs or links (e.g. #862)
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - low
        - medium
        - high
      default: low
