'use client'

import React, { useEffect, useRef, useState, useCallback } from 'react'
import { useReactFlow, useStore, ReactFlowState, MarkerType} from '@xyflow/react'
import useJsonConstructUtils, {NodeJsonType} from '../../hooks/useJsonConstructUtils'
import { nodeSmallProps } from '../nodeMenu/NodeMenu'
// import { useNodeContext } from '../../states/NodeContext'
import { useNodesPerFlowContext } from '../../states/NodesPerFlowContext'
// import PythonConfigEditor from '../tableComponent/PythonConfigEditor'
import isEqual from 'lodash/isEqual'

import { backend_IP_address_for_sendingData } from '../../hooks/useJsonConstructUtils'
import { ChooseConfigNodeData } from '../../workflow/edges/configNodes/ChooseConfig'
import { markerEnd } from '../../workflow/edges/ConfigToTargetEdge'
import { Select } from 'antd'
import useManageReactFlowUtils from '../../hooks/useManageReactFlowUtils'
import { nanoid } from 'nanoid'
import { json } from 'stream/consumers'
type ChooseConfigProps = {
    show: boolean,
    parentId: string,
}


// export type ChooseEdgeJsonType = {
//     id: string,
//     type: "choose",
//     data: {
//     switch: {id: string, label: string},
//     content: { id: string, label: string },
//     inputs: {id: string, label: string}[],
//     outputs: {id: string, label: string}[],
//     looped: boolean,
//     ON: {id: string, label: string}[],
//     OFF: {id: string, label: string}[]
//   }
// }


interface Condition {
    id: string;
    label: string;
    condition: string;
    type?: string;
    cond_v: string;
    cond_input?: string;
    operation?: string; // Optional, as it may not always be provided
}

interface Action {
    from_id: string;
    from_label: string;
    outputs: string[];
}

interface CaseItem {
    conditions: Condition[];
    actions: Action[];
}

interface TransformedCondition {
    block: string;
    condition: string;
    parameters: { [key: string]: string }; // Key-value pairs for parameters
    operation: string;
}

interface TransformedCase {
    conditions: TransformedCondition[];
    then: {
        from: string;
        to: string;
    };
}

interface TransformedCases {
    [key: string]: TransformedCase; // Dynamic keys for cases
}


export type ChooseEdgeJsonType = {
    type: "choose" | "ifelse",
    data: {
        switch?: { [key: string]: string },
        content?: { [key: string]: string },
        inputs: { [key: string]: string },
        outputs: { [key: string]: string },
        looped?: boolean,
        ON?: { [key: string]: string },
        OFF?: { [key: string]: string },
        cases?: any
    }
}

type ConstructedChooseJsonData = {
    blocks: { [key: string]: NodeJsonType },
    edges: { [key: string]: ChooseEdgeJsonType }
}

function ChooseConfigMenu({show, parentId}: ChooseConfigProps) {
    const menuRef = useRef<HTMLUListElement>(null)
    const {getNode, setNodes, setEdges, getEdges} = useReactFlow()
    const {getSourceNodeIdWithLabel, cleanJsonString, reportError, streamResultForMultipleNodes, resetLoadingUIForMultipleNodes} = useJsonConstructUtils()
    // const {addNode, addCount, allowActivateNode, clear, totalCount, searchNode} = useNodeContext()
    const {clearAll} = useNodesPerFlowContext()
    const {getResultNodes} = useManageReactFlowUtils()
    // const {getZoom, getViewport, getNode, flowToScreenPosition} = useReactFlow()
    const [switchValue, setSwitchValue] = useState<string | null>((getNode(parentId)?.data as ChooseConfigNodeData)?.switch ?? null)
    const [contentValue, setContentValue] = useState<string | null>((getNode(parentId)?.data as ChooseConfigNodeData)?.content ?? null)
    // const [resultNode, setResultNode] = useState<string | null>((getNode(parentId)?.data as CodeConfigNodeData)?.resultNode ?? null)
    const [outputs, setOutputs] = useState<string[]>(() => {
        const outputIds = (getNode(parentId)?.data as ChooseConfigNodeData)?.resultNodes 
        return outputIds ? outputIds : []
    })
    const [ON, setON] = useState<string[]>(() => {
        const ONIds = (getNode(parentId)?.data as ChooseConfigNodeData)?.ON
        return ONIds ?? []
    })
    const [OFF, setOFF] = useState<string[]>(() => {
        const OFFIds = (getNode(parentId)?.data as ChooseConfigNodeData)?.OFF
        return OFFIds ?? []
    })
    const switchRef = useRef<HTMLSelectElement>(null)
    const contentRef = useRef<HTMLSelectElement>(null)
    // const [isAddContext, setIsAddContext] = useState(true)
    const [isAddFlow, setIsAddFlow] = useState(true)
    const [isComplete, setIsComplete] = useState(true)
    const [autogenerated, setAutogenerated] = useState(false)
    const [shouldUpdateONOFF, setShouldUpdateONOFF] = useState(false)
    
    useEffect(() => {
        onSwitchValueChange()
    }, [switchValue])

    useEffect(() => {
        onContentValueChange()
    }, [contentValue])

    useEffect(() => {
        if (shouldUpdateONOFF) {
            setON(prevOn => prevOn.filter(node => outputs.includes(node)))
            setOFF(prevOff => prevOff.filter(node => outputs.includes(node)))
            setShouldUpdateONOFF(false)
        }
    }, [shouldUpdateONOFF])


    // useEffect(() => {
    //     if (autogenerated) return
    //     const newOutputs = getResultNodes(parentId)
    //     if (isEqual(outputs, newOutputs)) return
    //     setOutputs(newOutputs)
    //     onResultNodesChange(newOutputs)
    //     // console.log(ON.filter(node => newOutputs.includes(node)))
    //     setShouldUpdateONOFF(true)
       
    // }, [isEqual(outputs, getResultNodes(parentId))])
    useEffect(() => {
        if (autogenerated) return
        const newOutputs = getResultNodes(parentId)
        if (isEqual(outputs, newOutputs)) return
        setOutputs(newOutputs)
        onResultNodesChange(newOutputs)
        // console.log(ON.filter(node => newOutputs.includes(node)))
        setShouldUpdateONOFF(true)
       
    }, [isEqual(outputs, getResultNodes(parentId))])

    useEffect(() => {
        onONValueChange()
    }, [ON])

    useEffect(() => {
        onOFFValueChange()
    }, [OFF])

    // useEffect(() => {
    //     console.log(ON, "ON")
    //     console.log(OFF, "OFF")
    // }, [outputs])


    // useEffect(() => {
    //     setON(prevOn => prevOn.filter(node => outputs.includes(node)))
    //     setOFF(prevOff => prevOff.filter(node => outputs.includes(node)))
    // }, [outputs])
    //TODO
    useEffect(() => {

        if (!outputs.length) return
        if (isComplete) return
        console.log("send data useeffect")
    
        const addNewNodesEdgesIntoFlow = async () => {
            const parentEdgeNode = getNode(parentId)
            if (!parentEdgeNode) return
            // calculate rightside two ResultNodes x and y
            const centerY = parentEdgeNode.position.y - 96;
            const spacing = 288;
            const totalHeight = spacing * (outputs.length - 1)
            const startY = centerY - totalHeight / 2

            // 准备所有新节点
            const newNodes = outputs.map((output, index) => ({
                id: output,
                position: {
                    x: parentEdgeNode.position.x + 160,
                    y: startY + spacing * index
                },
                data: {  
                    content: "", 
                    label: output,
                    isLoading: false,
                    locked: false,
                    isInput: false,
                    isOutput: false,
                    editable: false,
                },
                type: 'text',
            }));

            console.log("newnodes",newNodes)

            // 准备所有新边
            const newEdges = outputs.map((output, index) => ({
                id: `connection-${Date.now() + index}`,
                source: parentId,
                target: output,
                // type: "CTT",
                type: "floating",
                data: {
                    connectionType: "CTT",
                },
                markerEnd: markerEnd,
            }));

            console.log("newedges",newEdges)
            await Promise.all([
                new Promise(resolve => {
                    setNodes(prevNodes => {
                        resolve(null);
                        return [...prevNodes, ...newNodes];
                    })
                }),
                new Promise(resolve => {
                    setEdges(prevEdges => {
                        resolve(null);
                        return [...prevEdges, ...newEdges];
                    })
                }),
            ]);

            console.log("updated",getNode(parentId))

            onResultNodesChange(outputs)
            setIsAddFlow(true)
        };

        const sendData = async  () => {
            console.log("senddata")
            try {
                const jsonData = constructJsonData()
                console.log("jsondata",jsonData)
                const response = await fetch(`${backend_IP_address_for_sendingData}`, {
                    method:'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify(jsonData)
                })

                if (!response.ok) {
                    for (let output of outputs) {
                        reportError(output, `HTTP Error: ${response.status}`)
                    }
                }
                
                console.log(response)
                const result = await response.json();  // 解析响应的 JSON 数据
                console.log('Success:', result);
                console.log(outputs, "your result node")
                await streamResultForMultipleNodes(result.task_id, outputs);
                
                } catch (error) {
                    console.warn(error)
                    window.alert(error)
                } finally {
                    resetLoadingUIForMultipleNodes(outputs)
                    setIsComplete(true)
                    // const realResultNode = getNode(resultNode.nodeid)
                    // if (!realResultNode) return
                    // if (resultNode.nodeType !== realResultNode.type) {
                    //     onResultNodeChange({
                    //         nodeid: resultNode.nodeid,
                    //         nodeType: realResultNode.type ?? "text"
                    //     })
                    //     setResultNode({
                    //         nodeid: resultNode.nodeid,
                    //         nodeType: realResultNode.type ?? "text"
                    //     })
                    // }
                }
        }
    
        if (!isAddFlow && !isComplete) {
            console.log("addNewNodesEdgesIntoFlow")
           addNewNodesEdgesIntoFlow()

        }
        else if (isAddFlow && !isComplete) {
            setAutogenerated(false)
            sendData()
        }
      }, [outputs, isAddFlow, isComplete])

      
    const onFocus: () => void = () => {
        const curRef = menuRef.current
        if (curRef && !curRef.classList.contains("nodrag")) {
            curRef.classList.add("nodrag")
        }
    }

    const onBlur: () => void = () => {
        const curRef = menuRef.current
        if (curRef) {
            curRef.classList.remove("nodrag")
        }
    }

    const displaySourceNodeLabels = () => {
        const sourceNodeIdWithLabelGroup = getSourceNodeIdWithLabel(parentId)
        return sourceNodeIdWithLabelGroup.map((node: {id: string, label: string}) => (
            <span key={`${node.id}-${parentId}`} className='w-fit text-[12px] font-[700] text-[#000] leading-normal tracking-[0.84px] bg-[#6D7177] px-[4px] flex items-center justify-center h-[16px] rounded-[6px] border-[#6D7177] border-[3px]'>{node.label}</span>
        ))
    }

    const displaySwitchLabels = () => {
        const sourceNodeIdWithLabelGroup = getSourceNodeIdWithLabel(parentId)
        const switchNodes = sourceNodeIdWithLabelGroup.filter(node => getNode(node.id)?.type === "switch")
        if (switchNodes.length > 0 && !switchValue) {
            setSwitchValue(switchNodes[0].id)
        }
        else if (switchNodes.length > 0 && switchValue) {
            if (!switchNodes.map(node => node.id).includes(switchValue)) {
                setSwitchValue(switchNodes[0].id)
            }
        }
        else if (switchNodes.length === 0 && switchValue) {
            setSwitchValue(null)
        }
        return switchNodes.map((node: {id: string, label: string}) => (
            <option key={`switch.${node.id}-${Date.now()}`} value={node.id}>
                {node.label}
            </option>
        ))
    }

    //to check if sourcenode is sturctured text
    const displayContentLabels = () => {
        const sourceNodeIdWithLabelGroup = getSourceNodeIdWithLabel(parentId)
        console.log(getNode(sourceNodeIdWithLabelGroup[0].id))
        const contentNodes = sourceNodeIdWithLabelGroup.filter(node => getNode(node.id)?.type === "text")
        if (contentNodes.length > 0 && !contentValue) {
            setContentValue(contentNodes[0].id)
        }
        else if (contentNodes.length > 0 && contentValue) {
            if (!contentNodes.map(node => node.id).includes(contentValue)) {
                setContentValue(contentNodes[0].id)
            }
        }
        else if (contentNodes.length === 0 && contentValue) {
            setContentValue(null)
        }
        return contentNodes.map((node: {id: string, label: string}) => (
            <option key={`content.${node.id}-${Date.now()}`} value={node.id}>
                {node.label}
            </option>
        ))
    }

    const displayOutputNodeLabels = () => {
        if (outputs.length === 0) return [].map((node: string) => (
            <span key={`${node}-${parentId}`} className='w-fit text-[12px] font-[700] text-[#000] leading-normal tracking-[0.84px] bg-[#6D7177] px-[4px] flex items-center justify-center h-[16px] rounded-[6px] border-[#6D7177] border-[3px]'>{getNode(node)?.data?.label as string ?? node}</span>
        ))

        return outputs.map((node: string) => (
            <span key={`${node}-${parentId}`} className='w-fit text-[12px] font-[700] text-[#000] leading-normal tracking-[0.84px] bg-[#6D7177] px-[4px] flex items-center justify-center h-[16px] rounded-[6px] border-[#6D7177] border-[3px]'>{getNode(node)?.data?.label as string ?? node}</span>
        ))
    }

    // const displayONLabels = () => {
    //     return outputs.map((node: string) => (
    //         <option key={`ON.${node}-${Date.now()}`} value={node}>
    //             {getNode(node)?.data?.label as string ?? node}
    //         </option>
    //     ))
    // }

    // const displayOFFLabels = () => {
    //     return outputs.map((node: string) => (
    //         <option key={`OFF.${node}-${Date.now()}`} value={node}>
    //             {getNode(node)?.data?.label as string ?? node}
    //         </option>
    //     ))
    // }

    const transformCases = (inputCases: CaseItem[]): { cases: TransformedCases } => {
        const transformedCases: TransformedCases = {};
    
        inputCases.forEach((caseItem, index) => {
            const caseKey = `case${index + 1}`; // Create case keys like "case1", "case2", etc.
            transformedCases[caseKey] = {
                conditions: caseItem.conditions.map(condition => ({
                    block: condition.id, // Assuming 'id' is the block identifier
                    condition: condition.cond_v,
                    parameters: { 
                        [condition.cond_v]: condition.cond_input || "" // Ensure this is a string
                    },
                    operation: condition.operation || "and" // Default to "and" if not provided
                })),
                then: {
                    from: caseItem.actions[0]?.from_id || "", // Get the from_id from actions
                    to: caseItem.actions[0]?.outputs[0] || "" // Get the first output
                }
            };
        });
    
        return { cases: transformedCases };
    };

    const constructJsonData = (): ConstructedChooseJsonData | Error => {
        console.log("constructjsondata","structuredValue")
        
        const contentNodes = getSourceNodeIdWithLabel(parentId).filter(node => getNode(node.id)?.type === "text")
        const switchNodes = getSourceNodeIdWithLabel(parentId).filter(node => getNode(node.id)?.type === "switch")
        const structuredNodes = getSourceNodeIdWithLabel(parentId).filter(node => getNode(node.id)?.type === "structured")
        
        const AllowedSourceNodes = [...contentNodes,...switchNodes,...structuredNodes]
        
        if (AllowedSourceNodes.length<=0 ) return new Error("switch or text or structured text is not selected as source");

        const sourceNodeIdWithLabelGroup = getSourceNodeIdWithLabel(parentId);
        let blocks: { [key: string]: NodeJsonType } = {};

        for (let output of outputs) {
            let resultNodeLabel;
            if (getNode(output) && getNode(output)?.data?.label !== undefined) {
                resultNodeLabel = getNode(output)?.data?.label as string;
            } else {
                resultNodeLabel = output;
            }

            const nodejson: NodeJsonType = {
                label: resultNodeLabel,
                type: "text",
                data: { content: "" }
            };
            blocks[output] = nodejson;
        }

        for (let sourceNodeIdWithLabel of sourceNodeIdWithLabelGroup) {
            const nodeInfo = getNode(sourceNodeIdWithLabel.id);
            if (!nodeInfo) continue;
            const nodeContent = (nodeInfo.type === "structured" || nodeInfo.type === "none" && nodeInfo.data?.subType === "structured") ? cleanJsonString(nodeInfo.data.content as string | any) : nodeInfo.data.content as string;
            if (nodeContent === "error") return new Error("JSON Parsing Error, please check JSON format");
            const nodejson: NodeJsonType = {
                label: (nodeInfo.data.label as string | undefined) ?? nodeInfo.id,
                type: nodeInfo.type!,
                data: {
                    content: nodeContent,
                }
            };
            blocks[nodeInfo.id] = nodejson;
        }

        let edges: { [key: string]: ChooseEdgeJsonType } = {};

        // [
        //     {
        //       "conditions": [
        //         {
        //           "id": "R7QmgN",
        //           "label": "R7QmgN",
        //           "condition": "",
        //           "type": "text",
        //           "cond_v": "contains",
        //           "cond_input": "dsa"
        //         }
        //       ],
        //       "actions": [
        //         {
        //           "from_id": "R7QmgN",
        //           "from_label": "R7QmgN",
        //           "outputs": [
        //             "7VrC5i"
        //           ]
        //         }
        //       ]
        //     },
        // case2
        //     {
        //       "conditions": [
        //         {
        //           "id": "R7QmgN", //block
        //           "label": "R7QmgN", 
        //           "condition": "", //condition
        //           "type": "text", 
        //           "cond_v": "contains",  // "parameters": {cond_v + " " + cond_input}
        //           "cond_input": "dsa" // "parameters": {cond_v + " " + cond_input}
        //           "operation": "and" // "operation"
        //         }
        //       ],
        //       "actions": [
        //         {
        //           "from_id": "R7QmgN", // then from
        //           "from_label": "R7QmgN",
        //           "outputs": [
        //             "7VrC5i"  //then to
        //           ]
        //         }
        //       ]
        //     }
        //   ]

        // "cases": {
        //     "case1": {
        //       "conditions": [
        //         {
        //           "block": "no1",
        //           "condition": "is_empty",
        //           "parameters": {},
        //           "operation": "and"
        //         },
        //         {
        //           "block": "no2",
        //           "condition": "is_empty",
        //           "parameters": {},
        //           "operation": "or"
        //         }
        //       ],
        //       "then": {
        //         "from": "",
        //         "to": ""
        //       }
        //     }

        console.log(JSON.stringify(cases))

        const casesdata =  transformCases(cases)

        // Constructing the new structure for IFELSE
        const edgejson: ChooseEdgeJsonType = {
            type: "ifelse",
            data: {
                cases: transformCases(cases),
                inputs: Object.fromEntries(sourceNodeIdWithLabelGroup.map((node: { id: string }) => ([node.id, ""]))), // Adjust inputs as needed
                outputs: Object.fromEntries(outputs.map((node: string) => ([node, ""]))) // Adjust outputs as needed
            }
        };

        const ifelseid = parentId.replace(/choose/g, 'ifelse');

        edges[ifelseid] = edgejson;

        return {
            blocks,
            edges
        };
    }


//     "IFELSE-124782085": {
//   "type": "ifelse",
//   "data": {
//     "cases": { 
// 	    "case1": {
// 		    "conditions": [
// 			    {"block": "no1", // block id
// 			    "condition": "is_empty",
// 			    "parameters": {}, // for conditions with params, e.g. contains xxx
// 			    "operation": "and"}, // can only be `and` or `or` or `/` for last condition
// 			    {"block": "no2",  // block id
// 			    "condition": "is_empty",
// 			    "parameters": {}, // for conditions with params, e.g. contains xxx
// 			    "operation": "or"}  // can only be `and` or `or` or `/` for last condition
// 		    ],
// 		    "then": {
// 			    "from":"",
// 			    "to":""
// 		    }
// 	    } 
//     },
//     "inputs": { "1": "", "2": "" },
//     "outputs": { "3": "", "4": "" }
//   }
// }

    
    const onDataSubmit = async () => {
          // click 第一步： clearActivation
          await new Promise(resolve => {
            clearAll()
            resolve(null)
        });

        console.log(outputs)

        // click 第二步： 如果 resultNode 不存在，则创建一个新的 resultNode
        if (!outputs.length){

            const newResultNodeOneId = nanoid(6)
            // onResultNodeChange(newResultNodeId)
            setAutogenerated(true)
            setOutputs([newResultNodeOneId])
            console.log(outputs)
            
            // setIsAddContext(false)
            setIsAddFlow(false)
        }
       
        // else if (outputs.length > 0 && outputs.map(output => getNode(output)).includes(undefined)) {
        //     const definedNodes = outputs.filter(output => getNode(output))
        //     if (definedNodes.length >= 2) {
        //         onResultNodesChange(definedNodes)
        //         setOutputs(definedNodes)
        //         allowActivateNode()
        //         clear()
        //         setIsAddContext(true)
        //         setIsAddFlow(true)
        //     }
        // }
         // click 第三步： 如果 resultNode 存在，则更新 resultNode 的 type 和 data
        else {
            // setNodes(prevNodes => prevNodes.map(node => {
            //     if (node.id === resultNode){
            //         return {...node, data: {...node.data, content: ""}}
            //     }
            //     return node
            // }))
            // onResultNodesChange(currentResultNodes)

            if (switchValue) {
                const switchNode = getNode(switchValue)
                const nodesWaitingForUpdate = switchNode?.data?.content as string === "ON" ? ON : OFF

                setNodes(prevNodes => prevNodes.map(node => {
                    if (nodesWaitingForUpdate.length > 0 && nodesWaitingForUpdate.includes(node.id)) {
                        return {...node, data: {...node.data, isLoading: true}}
                    }
                    return node
                }))
            }
            
            // setIsAddContext(true)
            // setIsAddFlow(true)
            // allowActivateNode()
            // clear()
        }
        setIsComplete(false)
        };

        // const onLoopChange = (newLoop: boolean) => {
        //     setNodes(prevNodes => prevNodes.map(node => {
        //         if (node.id === parentId) {
        //             return {...node, data: {...node.data, looped: newLoop}}
        //         }
        //         return node
        //     }))
        // }

    
        const onResultNodesChange = (newResultNodes: string[]) => {
            setNodes(prevNodes => prevNodes.map(node => {
                if (node.id === parentId) {
                    return {...node, data: {...node.data, resultNodes: newResultNodes}}
                }
                return node
            }))
        }

        const onSwitchValueChange = () => {
            setNodes(prevNodes => prevNodes.map(node => {
                if (node.id === parentId) {
                    return {...node, data: {...node.data, switch: switchValue}}
                }
                return node
            }))
        }

        const onContentValueChange = () => {
            setNodes(prevNodes => prevNodes.map(node => {
                if (node.id === parentId) {
                    return {...node, data: {...node.data, content: contentValue}}
                }
                return node
            }))
        }


        const onONValueChange = () => {
            setNodes(prevNodes => prevNodes.map(node => {
                if (node.id === parentId) {
                    return {...node, data: {...node.data, ON: ON}}
                }
                return node
            }))
        }

        const onOFFValueChange = () => {
            setNodes(prevNodes => prevNodes.map(node => {
                if (node.id === parentId) {
                    return {...node, data: {...node.data, OFF: OFF}}
                }
                return node
            }))
        }

        interface Condition {
            id: string;
            label: string;
            condition: string;
            type?: string;
            cond_v: string;
            cond_input?: string;
            operation: string;
        }
    
        interface Action {
            from_id: string;
            from_label:string;
            outputs:string[]
        }
    
        interface Case {
            conditions: Condition[];
            actions: Action[];
        }
    
        // TODO 3
        const [cases, setCases] = useState<Case[]>(getNode(parentId)?.data.cases as Case[] || []);
    

        useEffect(() => {
            setNodes(prevNodes => prevNodes.map(node => {
                if (node.id === parentId) {
                    return { ...node, data: { ...node.data, cases } }; // Update the cases in the node's data
                }
                return node;
            }));
            
            setTimeout(() => {
                console.log(getNode(parentId))
            }, 2000) // Log after 2 seconds
        }, [cases]); // Dependency array includes cases
    

        const [AND,OR] = ["and","or"]

        const onConditionAdd = (index: number) => () => {
            console.log("hello", index)
            setCases(prevCases => {
                return prevCases.map((caseItem, caseIndex) => {
                    if (caseIndex === index) {
                        return {
                            ...caseItem,
                            conditions: [
                                ...caseItem.conditions,
                                {
                                    id: `${caseItem.conditions.length + 1}`,
                                    label: `${caseItem.conditions.length + 1}`,
                                    condition: `condition${caseItem.conditions.length + 1}`,
                                    cond_v:'condition',
                                    operation:AND
                                }
                            ]
                        }
                    }
                    return caseItem
                })
            })
        }
    
        const onActionAdd = (index: number) => () => {
            console.log("hello", index)
            setCases(prevCases => {
                return prevCases.map((caseItem, caseIndex) => {
                    if (caseIndex === index) {
                        return {
                            ...caseItem,
                            actions: [
                                ...caseItem.actions,
                                {
                                    from_id: '',
                                    from_label: '',
                                    outputs: []
                                }
                            ]
                        }
                    }
                    return caseItem
                })
            })
        }

    
        const onCaseAdd = () => {
            console.log("outputs", outputs)
            setCases(prevCases => [
                ...prevCases,
                {
                    conditions: [
                        {
                            id: '',
                            label: '',
                            condition: '',
                            cond_v:'condition',
                            cond_input:"",
                            operation:AND
                        }
                    ],
                    actions: [
                        {
                            from_id: '',
                            from_label: '',
                            outputs: []
                        }
                    ]
                }
            ])
        }

        const getConditionSelections = (type:string) =>{
            console.log("GetConditionSelections",type)
            if(type === "text"){
                console.log("text")
                // contains XXX
                // doesn’t contain XXX
                // is greater than [N] characters
                // is less than [N] characters
                return ["contains", "doesn’t contain", "is greater than [N] characters", "is less than [N] characters"]
            }else if(type === "structured"){
            // is empty
            // is not empty
            // contains XXX
            // doesn’t contain XXX
            // is List
            // is Dict
            // length is greater than [N]
            // length is less than [N]
                return ["is empty", "contains", "doesn’t contain", "is greater than [N] characters", "is less than [N] characters", "list or dict"]
            }else if(type === "switch"){
                // (for Switch)
                // is True
                // is False
                return ["is True","is False"]
            }

            return []
        }

        const onConditionDelete = (caseIndex: number, conditionIndex: number) => () => {
            setCases(prevCases => {
                return prevCases.map((caseItem, index) => {
                    if (index === caseIndex) {
                        return {
                            ...caseItem,
                            conditions: caseItem.conditions.filter((_, condIndex) => condIndex !== conditionIndex)
                        };
                    }
                    return caseItem;
                });
            });
        };

        const onAndOrSwitch = (caseIndex: number, conditionIndex: number) => () => {
            setCases(prevCases => {
                return prevCases.map((caseItem, index) => {
                    if (index === caseIndex) {
                        return {
                            ...caseItem,
                            conditions: caseItem.conditions.map((condition, condIndex) => {
                                if (condIndex === conditionIndex) {
                                    return {
                                        ...condition,
                                        operation: condition.operation === AND ? OR : AND // Toggle operation
                                    };
                                }
                                return condition;
                            })
                        };
                    }
                    return caseItem;
                });
            });
        };
  
    
        return (

            <ul ref={menuRef} className={`w-[550px] absolute top-[58px] left-[0px] text-white rounded-[9px] border-[1px] border-[rgb(109,113,119)] bg-main-black-theme pt-[7px] pb-[6px] px-[6px] font-plus-jakarta-sans flex flex-col gap-[13px] ${show ? "" : "hidden"} `} >
                <li className='flex gap-1 items-center justify-between font-plus-jakarta-sans'>
                    <div className='flex flex-row gap-[8px] justify-center items-center'>
                        <div className='w-[24px] h-[24px] border-[1px] border-main-grey bg-main-black-theme rounded-[4px] flex items-center justify-center'>
                            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12" fill="none">
                            <path d="M6 12V7" stroke="#D9D9D9" strokeWidth="2"/>
                            <path d="M10 2V7L2 7V2" stroke="#D9D9D9" strokeWidth="1.5"/>
                            <path d="M0.934259 2.5L2 0.901388L3.06574 2.5H0.934259Z" fill="#D9D9D9" stroke="#D9D9D9"/>
                            <path d="M8.93426 2.5L10 0.901388L11.0657 2.5H8.93426Z" fill="#D9D9D9" stroke="#D9D9D9"/>
                            </svg>
                        </div>
                        <div className='flex items-center justify-center text-[12px] font-[600] text-main-grey font-plus-jakarta-sans leading-normal'>
                        Choose
                        </div>
                    </div>
                    <div className='w-[57px] h-[26px]'>
                        <button className='w-full h-full rounded-[6px] bg-[#39BC66] text-[#000] text-[12px] font-[700] font-plus-jakarta-sans flex flex-row items-center  justify-center gap-[7px]' onClick={onDataSubmit}>
                        <span>
                            <svg xmlns="http://www.w3.org/2000/svg" width="8" height="10" viewBox="0 0 8 10" fill="none">
                            <path d="M8 5L0 10V0L8 5Z" fill="black"/>
                            </svg>
                        </span>
                        <span>
                            Run
                        </span>
                        </button>
                    </div>
                </li>
                <li className='flex gap-1 items-center justify-start font-plus-jakarta-sans border-[1px] border-[#6D7177] rounded-[4px] w-[520px]'>
                    <div className='text-[#6D7177] w-[62px] font-plus-jakarta-sans text-[12px] font-[700] leading-normal px-[12px] py-[8px] border-r-[1px] border-[#6D7177] flex items-center justify-start'>
                     input
                    </div>
                    <div className='flex flex-row flex-wrap gap-[10px] items-center justify-start flex-1 py-[8px] px-[10px]'>
                        {displaySourceNodeLabels()}
                    </div>
                    
                </li>
                <li className='flex gap-1 items-center justify-start font-plus-jakarta-sans border-[1px] border-[#6D7177] rounded-[4px] w-[520px]'>
                    <div className='text-[#6D7177] w-[62px] font-plus-jakarta-sans text-[12px] font-[700] leading-normal px-[12px] py-[8px] border-r-[1px] border-[#6D7177] flex items-center justify-start'>
                     output
                    </div>
                    <div className='flex flex-row flex-wrap gap-[10px] items-center justify-start flex-1 py-[8px] px-[10px]'>
                        {displayOutputNodeLabels()}
                    </div>
                </li>
                {
                    cases.map((case_value,case_index)=>(
                        <li key={case_index} className='flex flex-col gap-1 items-start justify-center font-plus-jakarta-sans'>
                            <div className='text-[#6D7177] font-plus-jakarta-sans text-[12px] font-[700] leading-normal ml-[4px]'>
                            Case {case_index+1}
                            </div>
                            
                            <div className='flex flex-col border-[#6D7177] rounded-[4px] border-[1px] p-3'>
                                {
                                    case_value.conditions.map(
                                        (condition_value,conditions_index)=>(
                                            <>
                                                <label>IF</label>
                                                <div className='inline-flex space-x-2'>
                                                <button onClick={onConditionDelete(case_index, conditions_index)} className='w-[40px] cursor-pointer rounded-[15px] mt-0 ml-0 bg-black text-[#6D7177] pl-[3px] pr-[3px] font-plus-jakarta-sans text-[20px] font-[700] border-[1px] border-[#6D7177] items-center'>
                                                        -
                                                </button>
                                                <ul key={conditions_index} className='flex-col border-[#6D7177] rounded-[4px] min-w-[280px] bg-black'>
                                                    <li className='flex gap-1 items-center justify-start font-plus-jakarta-sans border-[1px] border-[#6D7177] rounded-[4px] min-w-[280px]'>
                                                        <div className='flex flex-row flex-wrap gap-[10px] items-center justify-start flex-1 py-[8px] px-[10px]'>
                                                        <select 
                                                            className='w-full bg-black text-white font-plus-jakarta-sans text-[12px] border-none outline-none w-[100px]'
                                                            onChange={(e) => {
                                                                const selectedNode = getSourceNodeIdWithLabel(parentId).find(
                                                                    node => node.id === e.target.value
                                                                );
                                                                if (selectedNode) {
                                                                    const cases_clone = [...cases];
                                                                    cases_clone[case_index].conditions[conditions_index] = {
                                                                        ...cases_clone[case_index].conditions[conditions_index],
                                                                        id: selectedNode.id,
                                                                        label: selectedNode.label,
                                                                        type: getNode(selectedNode.id)?.type
                                                                    };
                                                                    setCases(cases_clone);
                                                                    console.log("selected ndoe:", getNode(selectedNode.id))
                                                                }
                                                            }}
                                                            value={condition_value.id}
                                                        >
                                                            <option value="">Select a node</option>
                                                            {getSourceNodeIdWithLabel(parentId).map((node) => (
                                                                <option key={node.id} value={node.id}>
                                                                    {node.label || node.id}
                                                                </option>
                                                            ))}
                                                        </select>
                                                        </div>
                                                        <div className='text-[#6D7177] w-[190px] font-plus-jakarta-sans text-[12px] font-[700] leading-normal px-[12px] py-[8px] border-r-[1px] border-l-[1px] border-[#6D7177] flex items-center justify-start'>
                                                        {
                                                            getNode(cases[case_index].conditions[conditions_index].id)?.type === "structured" && (
                                                                <select 
                                                                    className='w-full bg-black text-white font-plus-jakarta-sans text-[12px] border-none outline-none w-[150px]'
                                                                    onChange={(e) => {
                                                
                                                                        if (e.target.value) {
                                                                            const cases_clone = [...cases];
                                                                            cases_clone[case_index].conditions[conditions_index] = {
                                                                                ...cases_clone[case_index].conditions[conditions_index],
                                                                                cond_v: e.target.value
                                                                            };
                                                                            setCases(cases_clone);
                                                                            console.log("cond_v",cases)
                                                                        }
                                                                    }}
                                                                    value={cases[case_index].conditions[conditions_index].cond_v}
                                                                >
                                                                    <option value=""> condition </option>
                                                                    {   
                                                                        getConditionSelections("structured").map((sl_v,sl_id) => (
                                                                            <option key={sl_id} value={sl_v}>
                                                                                {sl_v}
                                                                            </option>
                                                                        ))
                                                                    }
                                                                </select>
                                                            )
                                                            }
                                                            {               
                                                            getNode(cases[case_index].conditions[conditions_index].id)?.type === "text" && (
                                                                <select 
                                                                    className='w-full bg-black text-white font-plus-jakarta-sans text-[12px] w-[150px] border-none outline-none'
                                                                    onChange={(e) => {
                                                
                                                                        if (e.target.value) {
                                                                            const cases_clone = [...cases];
                                                                            cases_clone[case_index].conditions[conditions_index] = {
                                                                                ...cases_clone[case_index].conditions[conditions_index],
                                                                                cond_v: e.target.value
                                                                            };
                                                                            setCases(cases_clone);
                                                                            console.log("cond_v",cases)
                                                                        }
                                                                    }}
                                                                    value={cases[case_index].conditions[conditions_index].cond_v}
                                                                >
                                                                    <option value="">condition</option>
                                                                    {   
                                                                        getConditionSelections("text").map((sl_v,sl_id) => (
                                                                            <option key={sl_id} value={sl_v}>
                                                                                {sl_v}
                                                                            </option>
                                                                        ))
                                                                    }
                                                                </select>
                                                            )}
                                                            {
                                                            getNode(cases[case_index].conditions[conditions_index].id)?.type === "switch" && (
                                                                <select 
                                                                className='w-full bg-black text-white font-plus-jakarta-sans text-[12px] border-none outline-none'
                                                                onChange={(e) => {
                                            
                                                                    if (e.target.value) {
                                                                        const cases_clone = [...cases];
                                                                        cases_clone[case_index].conditions[conditions_index] = {
                                                                            ...cases_clone[case_index].conditions[conditions_index],
                                                                            cond_v: e.target.value
                                                                        };
                                                                        setCases(cases_clone);
                                                                        console.log("cond_v",cases)
                                                                    }
                                                                }}
                                                                value={cases[case_index].conditions[conditions_index].cond_v}
                                                            >
                                                                    <option value="">condition</option>
                                                                    {   
                                                                        getConditionSelections("switch").map((sl_v,sl_id) => (
                                                                            <option key={sl_id} value={sl_v}>
                                                                                {sl_v}
                                                                            </option>
                                                                        ))
                                                                    }
                                                                </select>
                                                            )
                                                        }
                                                        </div>
                                                        {
                                                            getNode(cases[case_index].conditions[conditions_index].id)?.type !== "switch" && (
                                                                <input 
                                                                value={cases[case_index].conditions[conditions_index].cond_input}
                                                                onChange={(e)=>{
                                                                    const cases_clone = [...cases];
                                                                    cases_clone[case_index].conditions[conditions_index] = {
                                                                        ...cases_clone[case_index].conditions[conditions_index],
                                                                        cond_input: e.target.value
                                                                    };
                                                                    setCases(cases_clone);
                                                                    console.log("cond_v",cases)
                                                                }} 
                                                                className="w-[100px] text-white bg-black caret-white"
                                                                type="text"></input>
                                                            )
                                                        }
                                                        
                                                    </li>
                                                </ul>
                                                {case_value.conditions.length - 1 === conditions_index ? (
                                                    <>
                                                    <span className='text-center align-baseline inline-block pt-[5px] w-[45px] text-transparent'>
                                                        AND
                                                    </span>
                                                    <button onClick={onConditionAdd(case_index)} className='cursor-pointer rounded-[15px] mt-0 ml-0 bg-black text-[#6D7177] pl-3 pr-3 font-plus-jakarta-sans text-[20px] font-[700] border-[1px] border-[#6D7177] items-center'>
                                                        +
                                                    </button>
                                                    </>
                                                ) : (
                                                    <>
                                                    <span className='text-center align-baseline inline-block pt-[5px] w-[40px]'>
                                                        {case_value.conditions[conditions_index].operation.toUpperCase()}
                                                    </span>
                                                    <button onClick={onAndOrSwitch(case_index, conditions_index)} className='cursor-pointer rounded-[15px] mt-0 ml-0 bg-black text-[#6D7177] pl-3 pr-3 font-plus-jakarta-sans text-[20px] font-[700] border-[1px] border-[#6D7177] items-center'>
                                                        #
                                                    </button>
                                                    </>
                                                )}
                                                </div>
                                            </>
                                        )
                                    )
                                }

                            </div>
        
                            <div className='flex flex-col border-[#6D7177] rounded-[4px] border-[1px] p-3 w-[535px]'>
                                {
                                    case_value.actions.map(
                                        (action_value, action_index) => (
                                            <>                                
                                                <label>THEN</label>
                                                <div className='inline-flex space-x-2'>
                                                    <button onClick={() => {
                                                                const cases_clone = [...cases];
                                                                cases_clone[case_index].actions.splice(action_index, 1); // Remove the action
                                                                setCases(cases_clone);
                                                            }} className='w-[40px] cursor-pointer rounded-[15px] mt-0 ml-0 bg-black text-[#6D7177] pl-[3px] pr-[3px] font-plus-jakarta-sans text-[20px] font-[700] border-[1px] border-[#6D7177] items-center'>
                                                                -
                                                    </button>
                                                    <ul className='flex flex-col border-[#6D7177] rounded-[4px] bg-black w-[370px]'>
                                                        <li className='flex gap-1 items-center justify-start font-plus-jakarta-sans border-[1px] border-[#6D7177] rounded-[4px] min-w-[280px]'>
                                                            <div className='flex flex-row flex-wrap gap-[10px] items-center justify-start flex-1 py-[8px] px-[10px]'>
                                                                <select 
                                                                    className='w-full bg-black text-white font-plus-jakarta-sans text-[12px] border-none outline-none'
                                                                    onChange={(e) => {
                                                                        const selectedNode = getSourceNodeIdWithLabel(parentId).find(
                                                                            node => node.id === e.target.value
                                                                        );
                                                                        if (selectedNode) {
                                                                            const cases_clone = [...cases];
                                                                            cases_clone[case_index].actions[action_index] = {
                                                                                ...cases_clone[case_index].actions[action_index],
                                                                                from_id: selectedNode.id,
                                                                                from_label: selectedNode.label
                                                                            };
                                                                            setCases(cases_clone);
                                                                        }
                                                                    }}
                                                                    value={action_value.from_id}
                                                                >
                                                                    <option value="">Select a node</option>
                                                                    {getSourceNodeIdWithLabel(parentId).map((node) => (
                                                                        <option key={node.id} value={node.id}>
                                                                            {node.label || node.id}
                                                                        </option>
                                                                    ))}
                                                                </select>
                                                            </div>
                                                            <div className='text-[#6D7177] font-plus-jakarta-sans text-[12px] font-[700] leading-normal px-[12px] py-[8px] border-r-[1px] border-l-[1px] border-[#6D7177] flex items-center justify-start'>
                                                                TO
                                                            </div>
                                                            <div className='flex flex-row flex-wrap gap-[10px] items-center justify-start flex-1 py-[8px] px-[10px]'>
                                                                <select 
                                                                    className='w-full bg-black text-white font-plus-jakarta-sans text-[12px] border-none outline-none'
                                                                    onChange={(e) => {
                                                                        const cases_clone = [...cases];
                                                                        cases_clone[case_index].actions[action_index].outputs = [e.target.value];
                                                                        setCases(cases_clone);
                                                                    }}
                                                                    value={action_value.outputs[0]}
                                                                >
                                                                    <option value="">Select output</option>
                                                                    {outputs.map((output) => (
                                                                        <option key={output} value={output}>
                                                                            {(getNode(output)?.data?.label as string) || output}
                                                                        </option>
                                                                    ))}
                                                                </select>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                    <span className='text-center align-baseline inline-block pt-[5px] w-[40px] text-transparent'>
                                                        AND
                                                    </span>
                                                    <button onClick={onActionAdd(case_index)} className='cursor-pointer rounded-[15px] mt-0 ml-0 bg-black text-[#6D7177] pl-3 pr-3 font-plus-jakarta-sans text-[20px] font-[700] border-[1px] border-[#6D7177] items-center'>
                                                        +
                                                    </button>
                                                </div>
                                            </>
                                        )
                                    )
                                }
                                
                            </div>
                        </li>
        
                    )
                    )
                }
                        <div className='flex flex-col items-center '>
                            <button onClick={onCaseAdd} className='rounded-[10px] bg-black text-[#6D7177] w-auto mt-1 pl-2 pr-2 font-plus-jakarta-sans text-[20px] font-[700] border-[1px] border-[#6D7177] items-center'>
                                + case
                            </button>
                        </div>
                
            </ul>
          )        
}

export default ChooseConfigMenu
