export type { WorkbenchTabSplitDropIntent as TerminalTabSplitDropIntent } from "../../app-shell/auxiliary-workbench/layout/workbenchTabMove";
export type { WorkbenchGroupMoveDropIntent as TerminalGroupMoveDropIntent } from "../../app-shell/auxiliary-workbench/layout/workbenchTabMove";
export type { WorkbenchGroupMergeDropIntent as TerminalGroupMergeDropIntent } from "../../app-shell/auxiliary-workbench/layout/workbenchTabMove";
export type { WorkbenchTabInsertDropIntent as TerminalTabInsertDropIntent } from "../../app-shell/auxiliary-workbench/layout/workbenchTabMove";
export type { WorkbenchTabMoveDropIntent as TerminalTabMoveDropIntent } from "../../app-shell/auxiliary-workbench/layout/workbenchTabMove";
export type { WorkbenchContentDropIntent as TerminalContentDropIntent } from "../../app-shell/auxiliary-workbench/layout/workbenchTabMove";
export type { WorkbenchTabBarDropIntent as TerminalTabBarDropIntent } from "../../app-shell/auxiliary-workbench/layout/workbenchTabMove";
export { partitionWorkbenchGroupDropIntent as partitionTerminalGroupDropIntent } from "../../app-shell/auxiliary-workbench/layout/workbenchTabMove";
export { WORKBENCH_TAB_DROP_PLACEHOLDER_ID as TERMINAL_TAB_DROP_PLACEHOLDER_ID } from "../../app-shell/auxiliary-workbench/layout/workbenchTabMove";
export { sameWorkbenchTabMoveDropIntent as sameTerminalTabMoveDropIntent } from "../../app-shell/auxiliary-workbench/layout/workbenchTabMove";
export type { WorkbenchTabInsertionPreview as TerminalTabInsertionPreview } from "../../app-shell/auxiliary-workbench/layout/workbenchTabMove";
export { projectWorkbenchTabInsertionPreview as projectTerminalTabInsertionPreview } from "../../app-shell/auxiliary-workbench/layout/workbenchTabMove";
export { projectWorkbenchGroupInsertionPreview as projectTerminalGroupInsertionPreview } from "../../app-shell/auxiliary-workbench/layout/workbenchTabMove";
