export type { WorkbenchSplitMinimumSize as TerminalSplitMinimumSize } from "../../app-shell/auxiliary-workbench/layout/workbenchSplitConstraints";
export type { WorkbenchSplitRatioBounds as TerminalSplitRatioBounds } from "../../app-shell/auxiliary-workbench/layout/workbenchSplitConstraints";
export { WORKBENCH_SPLIT_DIVIDER_SIZE as TERMINAL_SPLIT_DIVIDER_SIZE } from "../../app-shell/auxiliary-workbench/layout/workbenchSplitConstraints";
export { WORKBENCH_FALLBACK_MINIMUM_VIEWPORT as TERMINAL_FALLBACK_MINIMUM_VIEWPORT } from "../../app-shell/auxiliary-workbench/layout/workbenchSplitConstraints";
export { workbenchLeafMinimumSize as terminalLeafMinimumSize } from "../../app-shell/auxiliary-workbench/layout/workbenchSplitConstraints";
export { workbenchSplitNodeMinimumSize as terminalSplitNodeMinimumSize } from "../../app-shell/auxiliary-workbench/layout/workbenchSplitConstraints";
export { workbenchSplitChildMinimumSizes as terminalSplitChildMinimumSizes } from "../../app-shell/auxiliary-workbench/layout/workbenchSplitConstraints";
export { workbenchSplitRatioBounds as terminalSplitRatioBounds } from "../../app-shell/auxiliary-workbench/layout/workbenchSplitConstraints";
export { canPlaceWorkbenchSplit as canPlaceTerminalSplit } from "../../app-shell/auxiliary-workbench/layout/workbenchSplitConstraints";
export { clampWorkbenchRatioToBounds as clampTerminalRatioToBounds } from "../../app-shell/auxiliary-workbench/layout/workbenchSplitConstraints";
