"""
Folder Sync Engine — Data Models

Pure data structures independent of any business layer (L2/L2.5/L3).
Upper-layer wrappers (sync/folder_source, access/folder_access) add
business semantics (version management, auditing, etc.) on top of these structures.
"""

from dataclasses import dataclass, field
from typing import Any, Optional


# ============================================================
# File-level models
# ============================================================

@dataclass(frozen=True)
class FileEntry:
    """
    Metadata for a file in a directory (without content).

    frozen=True makes it hashable, convenient for use in set / dict.
    """
    rel_path: str
    content_hash: str
    content_type: str       # json | markdown | binary
    size_bytes: int
    modified_at: float      # os.path.getmtime


@dataclass
class FileContent:
    """File content + metadata. Return value of scanner.read_file()."""
    rel_path: str
    raw_bytes: bytes
    content: Any            # dict (JSON) | str (markdown/text)
    content_type: str       # json | markdown
    content_hash: str
    size_bytes: int


# ============================================================
# Change detection models
# ============================================================

@dataclass
class ChangeSet:
    """
    Difference between two snapshots. Return value of differ.diff_snapshots().

    Upper-layer wrappers decide how to handle based on business scenarios:
      - collection: created/modified -> ContentNodeService.update()
      - distribution: created/modified -> CollaborationService.commit()
    """
    created: list[FileEntry] = field(default_factory=list)
    modified: list[FileEntry] = field(default_factory=list)
    deleted: list[str] = field(default_factory=list)

    @property
    def is_empty(self) -> bool:
        return not self.created and not self.modified and not self.deleted

    @property
    def total(self) -> int:
        return len(self.created) + len(self.modified) + len(self.deleted)


# ============================================================
# Folder snapshot
# ============================================================

@dataclass
class FolderSnapshot:
    """
    Complete state of a folder at a point in time.

    Generated by scanner.scan_directory(), consumed by differ.diff_snapshots().
    Can be serialized and persisted for incremental comparison on next startup.
    """
    root_path: str
    entries: dict[str, FileEntry] = field(default_factory=dict)  # rel_path → FileEntry
    scanned_at: float = 0.0

    def get(self, rel_path: str) -> Optional[FileEntry]:
        return self.entries.get(rel_path)

    def to_dict(self) -> dict:
        """Serialize to a JSON-persistable dictionary."""
        return {
            "root_path": self.root_path,
            "scanned_at": self.scanned_at,
            "entries": {
                path: {
                    "content_hash": e.content_hash,
                    "content_type": e.content_type,
                    "size_bytes": e.size_bytes,
                    "modified_at": e.modified_at,
                }
                for path, e in self.entries.items()
            },
        }

    @classmethod
    def from_dict(cls, data: dict) -> "FolderSnapshot":
        """Restore from a persisted dictionary."""
        entries = {}
        for path, e in data.get("entries", {}).items():
            entries[path] = FileEntry(
                rel_path=path,
                content_hash=e["content_hash"],
                content_type=e["content_type"],
                size_bytes=e["size_bytes"],
                modified_at=e["modified_at"],
            )
        return cls(
            root_path=data.get("root_path", ""),
            entries=entries,
            scanned_at=data.get("scanned_at", 0.0),
        )
