#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

# ── Colors ───────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}▶${NC} $1"; }
ok()    { echo -e "${GREEN}✔${NC} $1"; }
warn()  { echo -e "${YELLOW}⚠${NC} $1"; }
fail()  { echo -e "${RED}✖ $1${NC}"; exit 1; }

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   PuppyOne — Local Development Setup     ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── Check prerequisites ─────────────────────────────────────
check_cmd() { command -v "$1" &>/dev/null || fail "$1 is required but not installed. $2"; }

check_cmd docker       "Install: https://docs.docker.com/get-docker/"
check_cmd node         "Install: https://nodejs.org/"
check_cmd python3      "Install: https://www.python.org/"
check_cmd npx          "Comes with Node.js"

if ! command -v uv &>/dev/null; then
  warn "uv not found. Installing..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
fi

ok "All prerequisites found"

# ── 1. Start Supabase ────────────────────────────────────────
info "Starting Supabase (PostgreSQL, Auth, Studio)..."

if npx supabase status &>/dev/null 2>&1; then
  ok "Supabase is already running"
else
  npx supabase start
fi

ok "Supabase is running"

# ── 2. Apply database migrations ────────────────────────────
info "Applying database migrations..."
npx supabase db push --include-all
ok "Database schema is up to date"

# ── 3. Capture Supabase credentials ─────────────────────────
info "Reading Supabase credentials..."

SUPABASE_API_URL=$(npx supabase status 2>/dev/null | grep "API URL" | awk '{print $NF}')
SUPABASE_ANON_KEY=$(npx supabase status 2>/dev/null | grep "anon key" | awk '{print $NF}')
SUPABASE_SERVICE_ROLE_KEY=$(npx supabase status 2>/dev/null | grep "service_role key" | awk '{print $NF}')
SUPABASE_JWT_SECRET=$(npx supabase status 2>/dev/null | grep "JWT secret" | awk '{print $NF}')
SUPABASE_DB_URL=$(npx supabase status 2>/dev/null | grep "DB URL" | awk '{print $NF}')

if [ -z "$SUPABASE_API_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
  fail "Could not read Supabase credentials. Run 'npx supabase status' to debug."
fi

ok "Supabase credentials captured"

# ── 4. Start Redis & MinIO ──────────────────────────────────
info "Starting Redis & MinIO..."
docker compose up -d
ok "Redis (6379) and MinIO (9000) are running"

# ── 5. Generate backend/.env ────────────────────────────────
info "Generating backend/.env..."

if [ -f backend/.env ]; then
  cp backend/.env "backend/.env.backup.$(date +%s)"
  warn "Existing backend/.env backed up"
fi

cat > backend/.env << EOF
# Auto-generated by scripts/setup.sh — $(date)

# ── App ──
APP_MODULE="src.main"
DEBUG="true"
PORT="9090"
PUBLIC_URL="http://localhost:9090"

# ── Internal ──
INTERNAL_API_SECRET="local-dev-secret-$(openssl rand -hex 8)"

# ── Supabase (from supabase start) ──
SUPABASE_URL="${SUPABASE_API_URL}"
SUPABASE_KEY="${SUPABASE_SERVICE_ROLE_KEY}"
SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY}"

# ── Auth ──
JWT_SECRET="${SUPABASE_JWT_SECRET}"
SKIP_AUTH="true"

# ── S3 / Storage (MinIO) ──
USE_REAL_S3="false"
S3_ENDPOINT_URL="http://localhost:9000"
S3_BUCKET_NAME="contextbase"
S3_REGION="us-east-1"
S3_ACCESS_KEY_ID="minioadmin"
S3_SECRET_ACCESS_KEY="minioadmin"

# ── LLM (optional — add your key to enable agent chat) ──
ANTHROPIC_API_KEY=""
ANTHROPIC_BASE_URL="https://api.anthropic.com"
ANTHROPIC_MODEL="claude-sonnet-4-20250514"

# ── Redis ──
ETL_REDIS_URL="redis://localhost:6379"

# ── MCP Server ──
MCP_SERVER_URL="http://localhost:9091"

# ── OCR / ETL ──
OCR_PROVIDER="deepseek"
ENABLE_ETL="false"

# ── Sandbox ──
SANDBOX="docker"
E2B_API_KEY=""
EOF

ok "backend/.env generated"

# ── 6. Generate frontend/.env ───────────────────────────────
info "Generating frontend/.env..."

if [ -f frontend/.env ]; then
  cp frontend/.env "frontend/.env.backup.$(date +%s)"
  warn "Existing frontend/.env backed up"
fi

cat > frontend/.env << EOF
# Auto-generated by scripts/setup.sh — $(date)
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
NEXT_PUBLIC_API_URL=http://localhost:9090
NEXT_PUBLIC_DEV_MODE=true
EOF

ok "frontend/.env generated"

# ── 7. Install & start backend ──────────────────────────────
info "Installing backend dependencies..."
cd "$ROOT_DIR/backend"
uv sync
ok "Backend dependencies installed"

info "Starting backend on :9090..."
uv run uvicorn src.main:app --host 0.0.0.0 --port 9090 --reload &
BACKEND_PID=$!

# ── 8. Install & start frontend ─────────────────────────────
info "Installing frontend dependencies..."
cd "$ROOT_DIR/frontend"
npm install
ok "Frontend dependencies installed"

info "Starting frontend on :3000..."
npm run dev &
FRONTEND_PID=$!

cd "$ROOT_DIR"

# ── Done ─────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║        PuppyOne is running! 🐶           ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Frontend         ${CYAN}http://localhost:3000${NC}"
echo -e "  Backend API      ${CYAN}http://localhost:9090${NC}"
echo -e "  Supabase Studio  ${CYAN}http://localhost:54323${NC}"
echo -e "  MinIO Console    ${CYAN}http://localhost:9001${NC}"
echo ""
echo -e "  Stop all:  ${YELLOW}kill $BACKEND_PID $FRONTEND_PID && docker compose down && npx supabase stop${NC}"
echo ""

wait
