import { version } from "./version.js";

// ── Character art frames generated from puppyone.svg via chafa ──
// Regenerate: chafa --size=65 --symbols ascii --colors=none <image>

const OPEN = [
  "            y@@@$$   yg$$$$$$$$$$$$$$$$$$$y   g$@@@L             ",
  "            $@@@@@  $@@@@@@@@@@@@@@@@@@@@@@@  9@@@@@             ",
  "            $@@@@F g@@@@@@@@@@@@@@@@@@@@@@@@@ 4@@@@@             ",
  "            @@@@@  $@@@@@@@@@@@@@@@@@@@@@@@@$  @@@@@             ",
  "           4@@@@@  $@@@@@@~R@@@@@@@@@F~@@@@@@  $@@@@L            ",
  "           g@@@@$  @@@@@@@@y`~@@@@P~yg@@@@@@@L $@@@@@            ",
  "           $@@@@F y@@@@@@@@~_y@@@@$y~~@@@@@@@L 4@@@@@            ",
  "             ~~~  a@@@@@@$yg@@@@@@@@@$y@@@@@@$  ~~~              ",
  "                  $@@@@@@@@@@@@@@@@@@@@@@@@@@@                   ",
  "                  @@@@@@@@@@   ===  4@@@@@@@@@L                  ",
  "                 u@@@@@@@@@@____ ___j@@@@@@@@@L                  ",
  "                 g@@@@@@@@@@@@@@ 4@@@@@@@@@@@@$                  ",
  "                 4@@@@@@@P@@@@@F_`@@@@@4@@@@@@P                  ",
  '                  ~@@@@@@@y_~_yg@gy_~_yg@@@@@F                   ',
  '                   "@@@@@@@@@@@@@@@@@@@@@@@@@~                    ',
  "                     4@@@@@@@@@@@@@@@@@@@@@                      ",
  "                      ~~~~~~~~~~~~~~~~~~~~                       ",
];

const BLINK = [
  "            4@@@g$   yggggggggggggggggggggy   ag@@@L             ",
  "            g@@@@F  g@@@@@@@@@@@@@@@@@@@@@@@  4@@@@$             ",
  "            $@@@@F y@@@@@@@@@@@@@@@@@@@@@@@@L 4@@@@@             ",
  "            @@@@@  g@@@@@@@@@@@@@@@@@@@@@@@@$  @@@@@             ",
  "           4@@@@@  $@@@@@@@@@@@@@@@@@@@@@@@@@  $@@@@L            ",
  "           g@@@@$  @@@@@@PPPPP@@@@@PPPPP@@@@@  $@@@@$            ",
  "           $@@@@F  @@@@@@ggggg@@@@@ggggg@@@@@L 4@@@@@            ",
  "             `~~  g@@@@@@@@@@@@@@@@@@@@@@@@@@$  ~~`              ",
  "                  $@@@@@@@@@@@@@@@@@@@@@@@@@@@                   ",
  "                  @@@@@@@@@@   ===  4@@@@@@@@@                   ",
  "                  @@@@@@@@@@____ ___j@@@@@@@@@L                  ",
  "                 g@@@@@@@@@@@@@@ 4@@@@@@@@@@@@$                  ",
  "                 4@@@@@@@P4@@@@F `@@@@@4@@@@@@F                  ",
  "                  ~@@@@@@@y_~__a@g__~_yg@@@@@F                   ",
  '                   `@@@@@@@@@@@@@@@@@@@@@@@@~                    ',
  "                     4@@@@@@@@@@@@@@@@@@@@P                      ",
  "                      ~~~~~~~~~~~~~~~~~~~~                       ",
];

// 17 lines × 65 cols (generated by chafa)

// ── Animation helpers ───────────────────────────────────────
const LINES = OPEN.length;
const GLITCH = "~<>{}|/\\xnrjf?!+_,.;:^#@&";
const DIM = "\x1b[38;5;240m";
const GY  = "\x1b[38;5;245m";
const DK  = "\x1b[38;5;238m";
const RST = "\x1b[0m";

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const pick  = () => GLITCH[Math.floor(Math.random() * GLITCH.length)];

function stripAnsi(s) {
  return s.replace(/\x1b\[[0-9;]*m/g, "");
}

function renderGlitch(art, mask) {
  let out = "";
  let idx = 0;
  for (const line of art) {
    const vis = stripAnsi(line);
    const codes = [];
    let ci = 0;
    const raw = line;
    let i = 0;
    while (i < raw.length) {
      if (raw[i] === "\x1b") {
        let end = raw.indexOf("m", i);
        const code = raw.substring(i, end + 1);
        i = end + 1;
        if (i < raw.length && raw[i] !== "\x1b") {
          const ch = raw[i];
          codes.push({ code, ch, visIdx: ci });
          ci++;
          i++;
        } else {
          let merged = code;
          while (i < raw.length && raw[i] === "\x1b") {
            let e2 = raw.indexOf("m", i);
            merged += raw.substring(i, e2 + 1);
            i = e2 + 1;
          }
          if (i < raw.length) {
            const ch = raw[i];
            codes.push({ code: merged, ch, visIdx: ci });
            ci++;
            i++;
          }
        }
      } else {
        codes.push({ code: "", ch: raw[i], visIdx: ci });
        ci++;
        i++;
      }
    }

    for (const { code, ch } of codes) {
      if (ch === " " || ch === "\n") {
        out += ch;
      } else if (mask[idx]) {
        out += code + ch;
      } else {
        out += DIM + pick();
      }
      idx++;
    }
    out += RST + "\n";
  }
  return out;
}

// ── Public API ──────────────────────────────────────────────
export async function showBanner() {
  if (!process.stdout.isTTY) return;

  const allVis = OPEN.map(stripAnsi).join("");
  const nonSpace = [];
  for (let i = 0; i < allVis.length; i++) {
    if (allVis[i] !== " ") nonSpace.push(i);
  }

  // Fisher-Yates shuffle
  for (let i = nonSpace.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [nonSpace[i], nonSpace[j]] = [nonSpace[j], nonSpace[i]];
  }

  const FRAMES = 14;
  const perFrame = Math.ceil(nonSpace.length / FRAMES);
  const mask = new Array(allVis.length).fill(false);
  const up = `\x1b[${LINES}A`;

  process.stdout.write("\x1b[?25l"); // hide cursor

  const restoreCursor = () => process.stdout.write("\x1b[?25h");
  const onExit = () => { restoreCursor(); process.exit(130); };
  process.on("SIGINT", onExit);

  try {
    // Phase 1: decode animation
    for (let f = 0; f < FRAMES; f++) {
      const s = f * perFrame;
      for (let k = s; k < Math.min(s + perFrame, nonSpace.length); k++) {
        mask[nonSpace[k]] = true;
      }
      if (f > 0) process.stdout.write(up);
      process.stdout.write(renderGlitch(OPEN, mask));
      await sleep(40);
    }

    // Final clean frame
    process.stdout.write(up);
    process.stdout.write(OPEN.join("\n") + "\n");

    // Phase 2: blink
    await sleep(500);
    for (let b = 0; b < 2; b++) {
      process.stdout.write(up);
      process.stdout.write(BLINK.join("\n") + "\n");
      await sleep(100);
      process.stdout.write(up);
      process.stdout.write(OPEN.join("\n") + "\n");
      if (b === 0) await sleep(600);
    }

    // Tagline
    process.stdout.write("\n");
    process.stdout.write(`${GY}  puppyone ${DK}v${version}${RST}\n`);
    process.stdout.write(`${DK}  cloud file system for AI agents${RST}\n\n`);

  } finally {
    process.off("SIGINT", onExit);
    restoreCursor();
  }
}
