create table public.etl_task (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id bigint null,
  project_id bigint null,
  filename text null,
  rule_id bigint null,
  status text null,
  progress bigint null,
  updated_at timestamp without time zone null,
  result jsonb null,
  error text null,
  metadata jsonb null,
  constraint etl_task_pkey primary key (id),
  constraint etl_task_project_id_fkey foreign KEY (project_id) references project (id),
  constraint etl_task_rule_id_fkey foreign KEY (rule_id) references etl_rule (id),
  constraint etl_task_user_id_fkey foreign KEY (user_id) references user_temp (id)
) TABLESPACE pg_default;