create table public.table (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  project_id bigint null,
  description text null,
  constraint table_pkey primary key (id),
  constraint table_project_id_fkey foreign KEY (project_id) references project (id)
) TABLESPACE pg_default;