create table public.user_temp (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  constraint user_temp_pkey primary key (id)
) TABLESPACE pg_default;