name: Deploy Schema to Qubits

on:
  push:
    branches:
      - qubits
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_schema-deploy.yml
    with:
      environment: staging
